### ISSUE TITLE
Hard to bundle in a pkg macos binary

### ISSUE THREAD

**Issue by makepanic** [microlinkhq/metascraper#105]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Hi there, 
Thanks for the great library.

I'm trying to package an app that depends on metascraper with [pkg](https://github.com/zeit/pkg).
I've stumbled over some issues when trying to bundle metascraper as a macos binary.

Using `resolve-from` to automatically resolve "known" metascraper packages doesn't really work on a package macos instance. (I'll investigate this next and maybe try to improve this upstream)

I've got around that by using the alternative method of creating a metascraper instance using `load([...packages])`.
This works, but fails as the `resolve-from` code will always run, even if not directly used.

The default module export [always creates the autoloading metascraper loader](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper/src/index.js#L21). If one removes that line, a `pkg` macos metascraper binary works fine.

This means packaging metascraper in a `pkg` macos binary is only possible if a developer copies [the index script](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper/src/index.js#L21) without the default `module.exports`.

I'm not sure if metascraper can do anything to improve this apart from maybe exposing a way to generate a metascraper instance loader function that isn't always trying to resolve known metascraper packages.

**Comment by Kikobeats** [comment]
Hey,

metascraper (v1) was initially a monolith project with all the rules mixed.

Then we move the rules into separate packages, so the user can require a specific rules set (v2).

To make possible migrate to v1 to v2 without too much breaking changes, we decided to keep `autoload` to load the most common rules set and export it as the main endpoint.

I think makes sense to remove it in a new v3 iteration, moving load as the default main endpoint:

```js
// v2: require('metascraper').load
// v3: require('metascraper')
const metascraper = require('metascraper')([
  require('metascraper-amazon')(),
  require('metascraper-youtube')(),
  require('metascraper-soundcloud')(),
  require('metascraper-image')(),
  require('metascraper-video')(),
  require('metascraper-author')(),
  require('metascraper-date')(),
  require('metascraper-description')(),
  require('metascraper-lang')(),
  require('metascraper-logo')(),
  require('metascraper-clearbit-logo')(),
  require('metascraper-logo-favicon')(),
  require('metascraper-publisher')(),
  require('metascraper-title')(),
  require('metascraper-url')()
])
```

This will remove some monkey patching code, and also and most important avoid ship rules set as part of the core, making the core smaller

**Comment by makepanic** [comment]
Nice, thanks for the quick work

**Comment by Kikobeats** [comment]
@makepanic If you generate the binary could be nice add a section into README about how to do that 🙂

**Comment by Kikobeats** [comment]
super 👍
