### ISSUE TITLE
Author field for YouTube video always returns 'NULL'

### ISSUE THREAD

**Issue by myfavsin** [microlinkhq/metascraper#107]
### Prerequisites

- [ ] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Subject of the issue

Describe your issue here.

### Steps to reproduce

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
Sorry but I'm going to close that, you need to complete the issue template or I can't help you
