### ISSUE TITLE
bundle rules as plugins?

### ISSUE THREAD

**Issue by ianstormtaylor** [microlinkhq/metascraper#11]
A bit more to think about after we nail the main API, but I was thinking that it feels weird for the bundled default rules to have such prominence, when they are for a pretty specific use case. Wondering instead if it might be nicer to make rules more of a plugin-system.

It could even maintain the same `(source, [rules])` API if that's still the simplest, although maybe it becomes a constructor with `new Metascraper(rules)` and then `.scrapeHtml()...` instead.

This would allow bundles of rules. The current set might be something like `metascraper-plugin-articles` but there could easily be a simple Open Graph one that doesn't handle fallbacks, as `metascraper-plugin-open-graph`, or whatever!

cc @blakeembrey for thoughts!

**Comment by blakeembrey** [comment]
Seems interesting. It's such a thin wrapper though, I'd probably go the other direction. Make the base a container of rules (new module, probably something generic for working with HTML/Cheerio) and have this module be an instance of that container with the rules that are already here?

**Comment by Kikobeats** [comment]
I opened an issue related with this right now, feedback is appreciated:
https://github.com/microlinkhq/metascraper/pull/41

Let's discuss on the PR comment, we can convert this into a reality 🙏
