### ISSUE TITLE
Request for CLI utility

### ISSUE THREAD

**Issue by kaushalmodi** [microlinkhq/metascraper#121]
Hello,

I am not a JS coder. Can you please wrap this library in a CLI utility. 

Hope is that with that, one can do below and that outputs the parsed JSON to stdout:

```
metascraper --url=URL --config=SCRAPER_OPTIONS.toml
```

(Or something like that.)

**Comment by Kikobeats** [comment]
Could be nice to have but in a different package like `metascraper-cli` but definitely not a must; you can query https://api.microlink.io/ directly to have a preview of how it looks.

**Comment by kaushalmodi** [comment]
@Kikobeats That's perfect! Would it be OK to use that API regularly? I plan to bake that API calls in a script that returns BibTeX entry for an input URL.

**Comment by Kikobeats** [comment]
I'm close this but PR are welcome
