### ISSUE TITLE
Problems with scraping from gazeta.pl and their partner services

### ISSUE THREAD

**Issue by palmiak** [microlinkhq/metascraper#125]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

When I'm trying to scrape data from:
http://www.wysokieobcasy.pl/wysokie-obcasy/7,163229,24028905,nie-czuje-sie-kompetentna-jeden-glos-nic-nie-zmieni-nie-chce.html

http://wiadomosci.gazeta.pl/wiadomosci/7,114884,24029653,glinski-o-klerze-ten-pan-z-waznego-tematu-zrobil-karykature.html#s=BoxOpLink

or others pages from this sites microlink returns mostly NULL
```
{
"lang":NULL
"author":NULL
"title":NULL
"publisher":NULL
"image":NULL
"description":NULL
"date":NULL
"logo":{
"url":"https://logo.clear ..."
"width":128
"height":128
"type":"png"
"size":11874
"size_pretty":"11.9 kB"
}
"url":"http://wiadomosci. ..."
}
```

### Steps to reproduce
Just try to pull data from those urls.

### Expected behaviour

There shouldn't be so many nulls. From what I see there are OG:tags etc so it should work fine.

### Actual behaviour

You get NULLs instead of data.

**Comment by Kikobeats** [comment]
I'm trying to reproduce but this URLs don't work under https, so I can't ¯\_(ツ)_/¯

**Comment by palmiak** [comment]
Hi @Kikobeats 

I see something has changed:
https://api.microlink.io/?url=http://wiadomosci.gazeta.pl/wiadomosci/7,114884,24029653,glinski-o-klerze-ten-pan-z-waznego-tematu-zrobil-karykature.html - this one is working correctly now.

But still https://api.microlink.io/?url=http://www.wysokieobcasy.pl/wysokie-obcasy/7,163229,24028905,nie-czuje-sie-kompetentna-jeden-glos-nic-nie-zmieni-nie-chce.html is not complete and I see there are og:tags and description in source.

**Comment by Kikobeats** [comment]
We made a little changes week ago improving follow redirects

Can you enter into our [chat](https://chat.microlink.io/) to help me debug it?
