### ISSUE TITLE
Metadata for the metadata (image should have width/height, etc)

### ISSUE THREAD

**Issue by burtonator** [microlinkhq/metascraper#128]
Images, video, etc should also have metadata.

We have an API internally that we've build out at Datastreamer... http://www.datastreamer.io/

I need something like this for Polar (https://getpolarized.io/) ... which is in Typescript.

Your framework seems pretty decent and close to what we have in Datastreamer. 

The main suggestion I have is that the metadata you provide doesn't have metadata.

For example, the image just is an URL but doesn't have width/height or format.  Video should have format, length in minutes.  

It looks like it could be extended though but if you've already fixed 'image' as a string it's harder.

**Comment by Kikobeats** [comment]
The purpose of this library is just extract data directly from the HTML markup.

You can use [microlink API](https://api.microlink.io/) for getting more contextual data, for example: https://api.microlink.io/?url=https://getpolarized.io&palette
