### ISSUE TITLE
[metascraper-facebook] Add Facebook specific connector

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/metascraper#134]
This connector is necessary because Facebook is not using any kind of metadata associated with their links.

### Subject of the issue

Twitter recommend to use
```html
<meta name="twitter:image" content="https://~~">
```
But facebook video preview page uses
```html
<meta property="twitter:image" content="https://~~">
```

metascraper-image only takes this one so cannot parse video preview
```javascript
$('meta[name="twitter:image"]').attr('content')
```

I think it is facebook's mistake but facebook would not fix it.
I just suggest to enhance this library's parseing coverage.
Maybe twitter:title, twitter:description also use property except name

It needs a URL validation similar:

- https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-amazon/index.js#L7
- https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-uol

**Testing URLs**

- https://www.facebook.com/193810163083/posts/10158606954363084/
- https://www.facebook.com/gmoneycambodia/videos/284008875784842

**Comment by Kikobeats** [comment]
Extended the issue with @shimika investigation, thanks for that!

**Comment by Kikobeats** [comment]
I tried to contact with facebook without success

https://twitter.com/Kikobeats/status/1172835892978999296

**Comment by Kikobeats** [comment]
This has been fixed!

Kudos to @jmperezperez for helping reach facebook dev team 👏

**Comment by Kikobeats** [comment]
This has been fixed!

Kudos to @JMPerez for helping reach facebook dev team 👏

**Comment by jamespacileo** [comment]
@Kikobeats How has this been fixed? Tried to get metadata out of Facebook events at the moment :)
