### ISSUE TITLE
[metascraper-description] Limit description field

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/metascraper#139]
Need to limit the `description` value if the size exceded a determinate length.

Based on [SEO](https://moz.com/blog/how-long-should-your-meta-description-be-2018) recomendations said that ~300 characters are enough good.

**Testing URLs**

- https://www.collaborativefund.com/blog/the-psychology-of-money
- https://www.foundmyfitness.com/news/s/blw1bx/using_the_sauna_4x_per_week_lowered_hypertension_by_46_in_men

**Comment by daviswhitehead** [comment]
It would be great if you made the description TRUNCATE_MAX_LENGTH a paramater that was available for change based on each developer's needs...

I'm not sure how to do that but willing to help if you give some direction!

**Comment by Kikobeats** [comment]
@daviswhitehead I created https://github.com/microlinkhq/metascraper/pull/191 for addressing that 👍

**Comment by daviswhitehead** [comment]
Awesome!
It looks good to me. Just had a couple of comments. Would love to get this merged in and shipped to NPM so I can use it :)

**Comment by daviswhitehead** [comment]
Hey @Kikobeats,

I just upgraded to the latest release with these changes and I haven't been able to get the scraper to pull a longer description :/. Any help or direction you can provide would be great!

Here's my require chain
```javascript
const metascraper = require('metascraper')([
  require('metascraper-description')({
    truncateLength: 5000
  }),
  require('metascraper-image')(),
  require('metascraper-logo')(),
  require('metascraper-clearbit-logo')(),
  require('metascraper-publisher')(),
  require('metascraper-title')(),
  require('metascraper-url')(),
  require('metascraper-readability')(),
  require('metascraper-audio')(),
  require('metascraper-soundcloud')(),
  require('metascraper-video')(),
  require('metascraper-youtube')()
]);
```

and my package.json dependencies
```json
    "metascraper": "^5.6.1",
    "metascraper-audio": "^5.6.1",
    "metascraper-author": "^5.6.1",
    "metascraper-clearbit-logo": "^5.3.0",
    "metascraper-description": "^5.6.1",
    "metascraper-image": "^5.6.1",
    "metascraper-logo": "^5.6.1",
    "metascraper-publisher": "^5.6.1",
    "metascraper-readability": "^5.6.1",
    "metascraper-soundcloud": "^5.6.1",
    "metascraper-title": "^5.6.1",
    "metascraper-url": "^5.6.1",
    "metascraper-video": "^5.6.1",
    "metascraper-youtube": "^5.6.1",
```

**Comment by Kikobeats** [comment]
I didn't merge and release the new version of the package yet!

**Comment by daviswhitehead** [comment]
For what it's worth, I discovered today after a bunch of digging that most of the description tags found by `metascraper-description` are already truncated within the html itself.

Just wanted to share that here before anyone else tries to get a longer description than what the scraper is returning.

Unrelated, this doc was super helpful in allowing me to dig in!
https://github.com/microlinkhq/metascraper/blob/master/CONTRIBUTING.md
