### ISSUE TITLE
[metascraper-manifest] Detect web apps manifests

### ISSUE THREAD

**Issue by ambrt** [microlinkhq/metascraper#147]
There is a way to describing domain data in webmanifest file https://developer.mozilla.org/en-US/docs/Web/Manifest

For example VueJs forum uses it https://forum.vuejs.org/manifest.webmanifest

It would be nice to include this way into metascraper.

**Comment by Kikobeats** [comment]
Hello,

What kind of information could be interesting that is only present on the manifest file and not in the HTML markup?

I feel all the relevant information can be extracted from the HTML markup, also you don't need an additional request for getting it.

**Comment by ambrt** [comment]
> What kind of information could be interesting that is only present on the manifest file and not in the HTML markup?

Basically i was looking for image related to a page. And as in example (vue forum) the "logo" is null and "image" is from content. (the mozilla logo is returned as "image" for https://forum.vuejs.org/t/vue-cli-v3-beta-where-to-put-the-favicon-ico/32161/2 ).

I've looked up source code and there is no favicon in head section. In manifest there is "icon" entry.
So i thought it might be a source for logo.

> You don't need an additional request for getting it.

Thats a valid reason.
Maybe second request to manifest could be a fallback if no logo is found.
It seems to be edge case, so no pressure.

**Comment by Kikobeats** [comment]
We can bundle the rules into a new `metascraper-manifest` connector.

Do you want to convert this into PR? 🙂

**Comment by ambrt** [comment]
I have little time ATM, so i couldn't code it now but it can be turned to PR for future reference.

**Comment by Kikobeats** [comment]
Happy to accept a metascraper connector addressing this; otherwise, I'm going to close the issue since this is not something esencial
