### ISSUE TITLE
Some links return 404

### ISSUE THREAD

**Issue by abelabbesnabi** [microlinkhq/metascraper#150]
Hi,

I'm using the latest version 4.9.0. Some links come back as 404.

Here's un example: https://www.mathventurepartners.com/blog/2019/1/10/math-101-the-rule-of-two

Any idea why?

**Comment by Kikobeats** [comment]
Hello,

I think you are not providing the HTML markup necessary to metascraper for detecting data.

In fact, [Microlink API](https://api.microlink.io/?url=https://www.mathventurepartners.com/blog/2019/1/10/math-101-the-rule-of-two) detects the major part of the data fields.

**Comment by abelabbesnabi** [comment]
What do you mean I'm not providing the metadata? This is not my link. I'm using your api to scrape this link.

**Comment by abelabbesnabi** [comment]
Hi, I know the link you provided works. How do you use this with the matascraper on node js? Do we have to call the MicroLink api? I'm trying to use the metascraper only.

**Comment by Kikobeats** [comment]
Just provide the HTML like the example into the README.

**Comment by abelabbesnabi** [comment]
Hi, 

You can consider this issue closed. This is no a metascraper issue. The request library that I use to pull the html and pass it to metascraper is in fact returning this:

<html>
<head>
<title>400 Bad Request</title>
<style> body { background-color: #F2F2F2; color: #3E3E3E; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; } pre { word-wrap: break-word; } </style>
</head>
<body>
<h1>400 Bad Request</h1>
<p><pre>ET87qNSy/taGznBj5 @ Mon, 21 Jan 2019 23:02:34 GMT</pre>
<p><pre>SEC-43</pre>
<p><pre></pre>
</body>
</html>

So, it's not the metascraper's fault.

Thanks for following up.
