### ISSUE TITLE
[metascraper-amazon] link not contemplated

### ISSUE THREAD

**Issue by abelabbesnabi** [microlinkhq/metascraper#151]
I'm using version 4.9.0.

None of the Amazon links work: https://www.amazon.com/Bounty-Quick-Size-Paper-Towels-Family/dp/B079VP6DH5/ref=lp_16310101_1_4_s_it?s=grocery&ie=UTF8&qid=1548086322&sr=1-4

Thanks.

**Comment by Kikobeats** [comment]
Hello,

I think is related the amazon link layer is too different for the rest of Amazon views supported.

Can you extend the metascraper amazon bundle rules and convert this into a PR? 🙂
