### ISSUE TITLE
NPM Reporting as CSS Vulnerability

### ISSUE THREAD

**Issue by WilliamHolmes** [microlinkhq/metascraper#153]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

NPM: `6.4.1`

### Subject of the issue
NPM Reporting as CSS Vulnerability

Describe your issue here.

![image](https://user-images.githubusercontent.com/5538260/52561553-9dd81e00-2df3-11e9-96bc-ad0f06a17893.png)

**Comment by Kikobeats** [comment]
maybe related with the same than https://github.com/microlinkhq/metascraper/pull/142?
