### ISSUE TITLE
Favicon & Domain Name

### ISSUE THREAD

**Issue by oyeanuj** [microlinkhq/metascraper#16]
Hi @ianstormtaylor! Does/can the library also return the favicon distinct from the image?

**Comment by ianstormtaylor** [comment]
Totally. I'd gladly accept a PR that adds that!

**Comment by oyeanuj** [comment]
Cool! Also, updated the title to reflect the two related quests.

**Comment by Kikobeats** [comment]
Hello,

I'm going to close this in favour to new [2.0.0](https://github.com/microlinkhq/metascraper/issues/40) add support for logo field, adding many rules related with favicon.

About domain, currently we have `publisher` and it is enough generic for use it. If you wan to use explicit the domain you can extract it from `url` field.
