### ISSUE TITLE
metascraper-logo-favicon should not issue a HEAD request

### ISSUE THREAD

**Issue by flunderpero** [microlinkhq/metascraper#161]
### Prerequisites

- [x] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Subject of the issue

`metascraper-logo-favicon` uses `[domain]/favicon.ico` as a fallback and then uses `got.head(...)` to verify that the favicon actually exists.

First of all this is surprising behaviour because metascraper never requests any URLs (afaik) and should not in my opinion. Besides that there are providers that do not answer HEAD requests and simply never return. https://immoscout.de is an example.

### Expected behaviour

Remove the HEAD request and either return `null` or `[domain]/favicon.ico`.

### Actual behaviour

The code hangs.

**Comment by Kikobeats** [comment]
Thanks for the issue. The associated PR should mitigate the problem.

Although the HEAD request is still here, now every request has a short timeout, hoping it reduces the inconvenient to have an external request.
