### ISSUE TITLE
paywall bundle?

### ISSUE THREAD

**Issue by jmensch1** [microlinkhq/metascraper#166]
Great package!

For my purposes, it would be nice if you could detect whether or not the article is behind a paywall. But I imagine that would be really hard. I haven't found any other packages that can do that.

**Comment by Kikobeats** [comment]
Hello, I think it could be hard since there is not a standard meta tag for reflecting that.

You can achieve something similar looking for keywords into the markup, but probably it's going to create a lot of false positives.
