### ISSUE TITLE
Instructions or guidelines for testing our own HTML selector rules

### ISSUE THREAD

**Issue by daviswhitehead** [microlinkhq/metascraper#170]
### Subject of the issue

Metascraper is an awesome library and I'd love to contribute. However, I'm struggling to develop my own HTML selector rules as I don't know how to begin testing them. Can anyone provide some instructions or guidelines or a tutorial on the best way to go about testing HTML selectors? I'm starting from a relatively basic set of knowledge...

For example, suppose I wanted to extract the name of a song from a youtube video. I can easily find in the HTML where the song name exists, but how do I develop and test an HTML selector rule to pull out the song name string?

![image](https://user-images.githubusercontent.com/8632165/57151576-46689f00-6d9f-11e9-9a01-d655722b9cfc.png)

Any help here would be super awesome as it would enable me to contribute additional scraper packages!

**Comment by Kikobeats** [comment]
Hello,

I added a [contribution](https://github.com/microlinkhq/metascraper/blob/master/CONTRIBUTING.md) guide in order to reduce the friction with that.

It is just a start! More things need to be added, feel totally free to suggest changes or creating PRs improving it 🙂
