### ISSUE TITLE
[metascraper-title] JSON LD support gives weird results on Wikipedia pages

### ISSUE THREAD

**Issue by jvandenaardweg** [microlinkhq/metascraper#176]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

`"metascraper-title": "^5.4.0",`

### Subject of the issue

Related to this change: https://github.com/microlinkhq/metascraper/pull/173

I have 100+ snapshot tests of crawler results and got some different results on Wikipedia pages when updating to the latest version of `metascraper-title` .

### Steps to reproduce
Crawl these random example URL's:
https://en.wikipedia.org/wiki/2018%E2%80%9319_UEFA_Champions_League
https://en.wikipedia.org/wiki/Newberry_Volcano

### Expected behaviour
Expected titles:
2018–19 UEFA Champions League
Newberry Volcano

### Actual behaviour
Actual titles:
the 64th season of Europe's premier club football tournament organised by UEFA
mountain in United States of America

So it seems Wikipedia does not use the `headline` property properly. It is used properly on some pages, but not all. So, the `title` result from metascraper becomes something you can't really rely on.

I doubt if the package should use JSON LD `headline` as preferable. `og`, `<title>` or `<h1>` should be looked at first imo.

### Change suggestion
Moving `wrap($jsonld('headline'))` down. I guess that makes it's priority lower. Haven't dived into the code to confirm this.

```javascript
'use strict'

const { $jsonld, $filter, title } = require('@metascraper/helpers')

const wrap = rule => ({ htmlDom, url }) => {
  const value = rule(htmlDom, url)
  return title(value)
}

module.exports = () => ({
  title: [
    wrap($ => $('meta[property="og:title"]').attr('content')),
    wrap($ => $('meta[name="twitter:title"]').attr('content')),
    wrap($ => $('.post-title').text()),
    wrap($ => $('.entry-title').text()),
    wrap($ => $('h1[class*="title" i] a').text()),
    wrap($ => $('h1[class*="title" i]').text()),
    wrap($jsonld('headline')),
    wrap($ => $filter($, $('title')))
  ]
})
```

**Comment by Kikobeats** [comment]
Let me try some combinations for determinating the best rule position 🙂

**Comment by prashnts** [comment]
I'd also like to point out that the images linked in `json-ld` are full-size images instead of the resized versions that open-graph properties usually use.

Few links where it happened:

- https://www.wired.com/2016/07/psychology-pokemon-go-gets-inside-brain/
- https://en.wikipedia.org/wiki/Northern_lapwing

I was getting crazy to see a 24MB image loading in a tiny 200px wide container!

PS: I was going to open a new issue, but this one seems to be related.
