### ISSUE TITLE
[metascraper-lang] Language detection based on content

### ISSUE THREAD

**Issue by SergeC** [microlinkhq/metascraper#177]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Use a language detector in case of being unable to parse language code from HTML.

### Steps to reproduce

If I parse a page https://medium.com/@ger86/un-mes-de-symfony-mayo-2019-y-novedades-de-symfony-4-3-143a7e63d870 I get ""lang": null,". Which is OK since language code can't be parsed from HTML. Page language can be detected with a library like https://github.com/wooorm/franc. 

I was trying to implement my own plugin, but I can't get a title and description, parsed by other plugins, from my new plugin to run Franc on the already extracted title and description. I also need to somehow add my new rules to "lang" array of rules. @Kikobeats Is it possible to implement language detection this way?

### Expected behavior

A "lang" code detected from the text.

### Actual behavior

Empty "lang"

**Comment by Kikobeats** [comment]
I think it is viable, but the thing necessary is to determinate the input to pass to `franc`.

Probably something like `$('body').text()` is too generic but not sure what is the right value.

Maybe @wooorm can say something based on his experience 🙂

**Comment by SergeC** [comment]
I wanted to start with "title" parsed with https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-title and "description" parsed with https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-description . Should be enough to detect most of the languages.

**Comment by wooorm** [comment]
That page does seem like there is one `lang` specified, on the article it states `[lang=es]`!

Automatic language detection won’t ever be perfect, but projects like Franc and [CLD](https://github.com/dachev/node-cld) do provide an alternative. Franc is slower and supports more languages (±400 max), which is good for including people, but it’s bad for the chances of something being English or Spanish (CLD is better at that, but supports like 50 languages).

With rehype it would be possible and pretty performant to detect the language (in this case, on `[lang=es]`) btw. Franc and CLD are useful as fallbacks.

**Comment by SergeC** [comment]
Right. My idea is to use Franc as a fallback since not possible to hardcode all possible attributes and they are not always available.

**Comment by Kikobeats** [comment]
Data rules run on parallel so no possible share result between them.

I feel this is a bit out of metascraper context, being it normalized meta tags present in the markup.

For now, I'm going skip add this as a core thing since actually is pretty simple just put a bit of code around metascraper output:


```js
const meta = metascraper(...)

if (!(meta.lang)) {
    const content = meta.description || meta.title
    if (content) {
      const langDetected = franc(content)
      if (langDetected) meta.lang = content
    }
  }
```
