### ISSUE TITLE
This package can't run in Edge

### ISSUE THREAD

**Issue by thminhVN** [microlinkhq/metascraper#180]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

This package can't run in Edge

### Steps to reproduce

Import this package and run in Edge with Babel 7

### Expected behaviour

Run nomarlly with babel preset env for object rest spread

### Actual behaviour

Can't run because Edge can run object rest spread

**Comment by Kikobeats** [comment]
although any effort here is welcome, this package is oriented to be run into a backend environment, so this is something expected
