### ISSUE TITLE
Inconsistent parse results

### ISSUE THREAD

**Issue by SergeC** [microlinkhq/metascraper#185]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

I execute parse multiple times of URL `https://medium.com/@raycodingjourney/title-%E5%8F%96%E5%BE%97-facebook-%E9%95%B7%E6%9C%9F%E6%AC%8A%E6%9D%96-long-lived-token-%E4%BB%A5%E5%8F%8A-%E6%B0%B8%E4%B8%8D%E9%81%8E%E6%9C%9F%E6%AC%8A%E6%9D%96-never-expired-token-b3f5746f953b` and get random results in `lang` field, its `en` or null.

I created my own lang plugin to parse Medium articles language.
`'use strict';

module.exports = () => ({
    lang_medium: [
        // parse language from Medium
        ({htmlDom}) => htmlDom('article[lang]').attr('lang'),
    ]
});`

With this plugin, I get the same random results.

### Steps to reproduce

1. Install a plugin from above.
`const metascraper = require('metascraper')([
    require('metascraper-lang')(),
    require('./plugins/lang')(),
]);`

2. Parse given URL mulltiple times

### Expected behaviour

The `lang_medium` field to be parsed from HTML

### Actual behaviour

Sometimes its `lang_medium` and `lang` fields are `null` but should contain language parsed from HTML.

**Comment by Kikobeats** [comment]
The output will be consistent as long as the input is consistent as well.

How are you providing the HTML?

**Comment by SergeC** [comment]
I ran it a few times and got inconsistent results for `lang` and `lang_medium` fields while other fields are consistent. Here is a code to reproduce.

 const metascraper = require('metascraper')([
    require('metascraper-author')(),
    require('metascraper-date')(),
    require('metascraper-description')(),
    require('metascraper-image')(),
    require('metascraper-logo')(),
    require('metascraper-publisher')(),
    require('metascraper-title')(),
    require('metascraper-lang')(),
    require('metascraper-url')(),
    require('./plugins/lang')(),
]);
const req = require('request-promise-native');
const url = 'https://medium.com/@raycodingjourney/title-%E5%8F%96%E5%BE%97-facebook-%E9%95%B7%E6%9C%9F%E6%AC%8A%E6%9D%96-long-lived-token-%E4%BB%A5%E5%8F%8A-%E6%B0%B8%E4%B8%8D%E9%81%8E%E6%9C%9F%E6%AC%8A%E6%9D%96-never-expired-token-b3f5746f953b';

req
    .get({
        uri: url,
        timeout: 30000,
        gzip: true,
        headers: {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3325.181 Safari/537.36'
        }
    })
    .then(html => metascraper({html, url: url}))
    .then(console.log)
    .catch(e => console.error(e, url));

**Sample results:**

{
  author: 'Ray Lee | 李宗叡',
  date: '2019-06-21T09:44:03.239Z',
  description: '本篇將分享如何利用 Facebook 的圖形 API 測試工具，以及 PHP 來取得長期權杖 (long ' +
    'lived token)，以及永不過期權杖 (never expired token)My Blog',
  image: 'https://cdn-images-1.medium.com/max/1200/0*Bq7O4Y72abRtKxBK.png',
  logo: 'https://cdn-images-1.medium.com/max/616/1*OMF3fSqH8t4xBJ9-6oZDZw.png',
  publisher: 'Medium',
  title: 'title: 取得 Facebook 長期權杖 (long lived token)，以及 永不過期權杖 (never expired token)',
  lang: null,
  url: 'https://medium.com/@raycodingjourney/title-%E5%8F%96%E5%BE%97-facebook-%E9%95%B7%E6%9C%9F%E6%AC%8A%E6%9D%96-long-lived-token-%E4%BB%A5%E5%8F%8A-%E6%B0%B8%E4%B8%8D%E9%81%8E%E6%9C%9F%E6%AC%8A%E6%9D%96-never-expired-token-b3f5746f953b',
  lang_medium: 'zh-Hant'
}

{
  author: 'Ray Lee | 李宗叡',
  date: '2019-06-21T09:44:03.239Z',
  description: '本篇將分享如何利用 Facebook 的圖形 API 測試工具，以及 PHP 來取得長期權杖 (long ' +
    'lived token)，以及永不過期權杖 (never expired token)My Blog',
  image: 'https://miro.medium.com/max/1200/0*Bq7O4Y72abRtKxBK.png',
  logo: 'https://miro.medium.com/max/1090/1*OMF3fSqH8t4xBJ9-6oZDZw.png',
  publisher: 'Medium',
  title: 'title: 取得 Facebook 長期權杖 (long lived token)，以及 永不過期權杖 (never expired token)',
  lang: 'en',
  url: 'https://medium.com/@raycodingjourney/title-%E5%8F%96%E5%BE%97-facebook-%E9%95%B7%E6%9C%9F%E6%AC%8A%E6%9D%96-long-lived-token-%E4%BB%A5%E5%8F%8A-%E6%B0%B8%E4%B8%8D%E9%81%8E%E6%9C%9F%E6%AC%8A%E6%9D%96-never-expired-token-b3f5746f953b',
  lang_medium: null
}

**Comment by Kikobeats** [comment]
but again, if Medium is serving you different HTML between requests, then probably a different rule is matching the result every time.

**Comment by SergeC** [comment]
Seems like Medium serves different HTML pages. If I read HTML from FS results are consistent.

**Comment by Kikobeats** [comment]
👍
