### ISSUE TITLE
[metascraper-title] Titles with dashes "-" incorrectly parsed

### ISSUE THREAD

**Issue by jvandenaardweg** [microlinkhq/metascraper#186]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

When upgrading from 5.3.4 to 5.5.2 i've noticed titles with dashes `-` in it get parsed incorrectly. See actual behaviour below.

### Steps to reproduce

Use the URL's below

### Expected behaviour

Should parse like it was before, in version 5.3.4

### Actual behaviour

Few examples:

5.3.4
1. [Friend portability is the must-have Facebook regulation – TechCrunch](https://techcrunch.com/2019/05/12/friends-wherever/)
2. [Jeff Bezos Unveils Blue Origin’s Lunar Lander; Announces Launch Of Next-Gen Rocket In 2021](https://www.forbes.com/sites/alexknapp/2019/05/09/jeff-bezos-unveils-blue-origins-lunar-lander-announces-new-glenn-first-launch-for-2021/)
3. [Trade-War Scenarios Force Investors to Rewrite Playbook](https://www.bloomberg.com/news/articles/2019-05-12/trade-war-scenarios-force-investors-to-rewrite-playbook)

5.5.2
1. Friend portability is the must
2. Jeff Bezos Unveils Blue Origin’s Lunar Lander; Announces Launch Of Next
3. Trade

I think it has something to do with this commit: https://github.com/microlinkhq/metascraper/commit/59e20d0d3bb0806baad8e9c4287c11684cd5c4e9#diff-0496017c7e648bc64614acafe9592cd6

Guess it could be fixed by using spaces in between: `[space]-[space]` or `[space]|[space]` on the `REGEX_TITLE_SEPARATOR`

**Comment by Kikobeats** [comment]
That is related with this helper: https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/index.js#L100

Cases need to be added here:
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/test/index.js#L211

Can you create a PR? 🙂

**Comment by Kikobeats** [comment]
Reproducible case: https://regex101.com/r/WY6EW9/1/

It only needs to consider ` - ` (with whitespaces), never `-` alone.

**Comment by SergeC** [comment]
I have the same issue. Maybe it's better not to edit content. If some need to remove `publisher` from a title he can do it manually afterward. @Kikobeats is any chance to fix it soon?

**Comment by Kikobeats** [comment]
What do you think if limit removes title separator just for `title` rule?

https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-title/index.js#L14

**Comment by SergeC** [comment]
I see two options:
1. Return `title` with applied filters and `title_raw` a title as is, without any filters applied.
2. Return `title` without any filters applied and provide a set of helper functions so developers can use them to post-process title.
