### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by osdiab** [microlinkhq/metascraper#195]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

TypeScript types would be really nice! I may add some to [`DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped), but in-repo always preferable.

### Steps to reproduce

Look at code, they're not there

### Expected behaviour

They ought to be there

### Actual behaviour

But hey, they aren't!

**Comment by Kikobeats** [comment]
Sure! I'm not using TypeScript but happy to accept a PR over this 🙂

**Comment by Kikobeats** [comment]
Happy to accept a PR in this direction; I'm going to close the issue since I'm not going to do it actively!

**Comment by salazarr-js** [comment]
@osdiab how can I help adding `.d.ts` types? is there any update about this?

**Comment by osdiab** [comment]
I didn't do anything and didn't end up using `metascraper` for my use case so no updates on my side
