### ISSUE TITLE
[metascraper-clearbit] 1000 ms timeout should be configurable

### ISSUE THREAD

**Issue by osdiab** [microlinkhq/metascraper#196]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

I expected `metascraper-clearbit` to properly fetch the logo for a given URL, but it intermittently returns `null` for the logo instead. I found this is because I'm using the library from Japan, and the timeout for the clearbit API request is not configurable, set to 1000. When I edited the library directly in `node_modules/`, it suddenly started working far more reliably.

On a related note, there ought to be some way to detect errors, they're useful to know - I was confused for some time because of this.

### Steps to reproduce

Get on a high-latency connection and try to use `metascraper-clearbit` (i.e., with the demo code). You can simulate this by editing `metascraper-clearbit` to have an unreasonably short timeout in the `got` request, and then rather than squelching errors in the `try/catch` in the code, log them.

### Expected behaviour

`logo` should get a Clearbit logo, because running that URL in [the Clearbit Logo API demo page](https://clearbit.com/logo) does produce one

### Actual behaviour

You get `null` instead, and if you do the above, then you'll see a TIMEOUT error.

**Comment by Kikobeats** [comment]
Makes total sense to me move this value as part of the module parameters.

Can you make a PR?

Also, What's could be a better default value?

**Comment by osdiab** [comment]
Sure! I'll give it a go.

I don't know what is a better default, but it wouldn't be a huge problem if there were some method for passing back errors. Not sure if there's any prior art for that in Metascraper yet, but if there isn't then that would definitely be issue worthy!.

**Comment by Kikobeats** [comment]
In my experience using metascraper on production scenarios, one second should be enough for resolving a simple GET
