### ISSUE TITLE
Get weight field on Amazon

### ISSUE THREAD

**Issue by juadiga** [microlinkhq/metascraper#201]
### Prerequisites

- [x ] I'm using the last version.
- [x ] My node version is the same as declared as `package.json`.

### Subject of the issue
Good day, how do I get the weight of a product by URL in Amazon?
Thank you

**Comment by Kikobeats** [comment]
Hey,

Actually, I don't know. Although we have a [metascraper-amazon](https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-amazon) package, it's oriented for matching generic data.

Can you tell more about what are you doing? what is the target URL? 

A screenshot could be helpful 🙂

**Comment by juadiga** [comment]
Thank you @Kikobeats 
For a web service it is required to calculate the shipping price plus the weight of the product.
So I would like to know how I can get that variable

**Comment by juadiga** [comment]
Thank you @Kikobeats .
For a web service it is required to calculate the shipping price with the weight of the product.
So I would like to know how I can get that variable

**Comment by juadiga** [comment]
![Captura de pantalla de 2019-08-09 08-13-16](https://user-images.githubusercontent.com/17294306/62781512-c88ef080-ba7d-11e9-9df9-f4f95d9f24fd.png)
Example for: [`URL Producto`](https://www.amazon.com/Garmin-Performance-Computer-Monitoring-Popularity/dp/B07QBDG3TR/ref=sr_1_3?crid=V5GDXXOZKTB4&keywords=garmin+530&qid=1564582676&s=gateway&sprefix=garmin+53%2Caps%2C214&sr=8-3)
