### ISSUE TITLE
I try to get metadata from URL NOT WORK

### ISSUE THREAD

**Issue by dverdugo85** [microlinkhq/metascraper#205]
### Prerequisites

- [5.6 ] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Subject of the issue

I can get metada from this url this url https://scotch.io/tutorials/building-a-react-native-app-as-a-designer-using-builderx.

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
It works fine to me:

https://api.microlink.io/?url=https://scotch.io/tutorials/building-a-react-native-app-as-a-designer-using-builderx

be sure you pass good HTML to the library.
