### ISSUE TITLE
I try to get metadata from URL NOT WORK

### ISSUE THREAD

**Issue by dverdugo85** [microlinkhq/metascraper#217]
### Prerequisites

- [5.7.6 ] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Subject of the issue

Describe your issue here.

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

Hello!!!

I can´t get metadata from this url **https://music.youtube.com/watch?v=MaCnp-yB-Yc&feature=share.**

> THE LOG IS 

```
{
        author:null,
        date:null,
        description:null,
        image:
        'https://s.ytimg.com/yts/img/music/web/on_platform_logo_dark-vflUWXsGq.png',
        logo:'https://logo.clearbit.com/youtube.com',
        publisher:'YouTube',
        title:'Your browser is deprecated. Please upgrade.',
        url:
        'https://music.youtube.com/watch?v=MaCnp-yB-Yc&feature=share'

        }
```

Regards!!!

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
metascraper needs to be called with properly HTML for extracting content, so getting that HTML is not part of this repository.

Saying that, consider use [microlink](https://microlink.io) 🙂

https://api.microlink.io/?url=https://music.youtube.com/watch?v=MaCnp-yB-Yc

**Comment by dverdugo85** [comment]
Thanks @Kikobeats

**Comment by dverdugo85** [comment]
I try to load this links!! thath not work http://www.radioceania.cl/radio/radioonline/ 


LOG

> {"data":{"url":"The `url` as `http://www.radioceania.cl/radio/radioonline/` reached timeout after 23s."},"more":"https://microlink.io/docs/api/parameters/url","code":"ETIMEOUT","message":"The request has been not processed. See the errors above to know why.","status":"fail"}



Regards!!
