### ISSUE TITLE
Not get Image metadata!!

### ISSUE THREAD

**Issue by dverdugo85** [microlinkhq/metascraper#218]
### Prerequisites

- [ 5.7.6] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Subject of the issue

Hello!!!
Not get the  url image from this site:  

> http://agenda.udec.cl/?q=content/obra-%E2%80%9Ccuerpo-fronterizo%E2%80%9D

`I find in the html this image url :http://agenda.udec.cl/sites/default/files/styles/imagenes_eventos_udec/public/cuerpo.jpg?itok=c4XF6H_X`

but the library show this link from image : 

> http://agenda.udec.cl/sites/all/modules/lazyloader/image_placeholder.gif

regards!!!

Describe your issue here.

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
Using Microlink API the `image` is `null` as well:
https://api.microlink.io/?url=http%3A%2F%2Fagenda.udec.cl%2F%3Fq%3Dcontent%2Fobra-“cuerpo-fronterizo”&prerender=false

That's because the HTML should to have one of these rules: 
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-image/index.js#L22

I not seeing nothing there the library can considered as image

**Comment by dverdugo85** [comment]
@Kikobeats  thansk!!! for your help!!
 I try from other URL to get image.... this url  is the facebook that  I can not get url image correct 

reference: https://www.facebook.com/LaBioguia/videos/519973161895637/

**Comment by dverdugo85** [comment]
I try with https://api.microlink.io/?url=https://www.facebook.com/LaBioguia/videos/519973161895637/

show this:

`{"data":{"title":"Un bocadito más y mañana arranco la dieta...","description":"Un bocadito más y mañana arranco la dieta...\nCréditos: IG @cruzysuzy","lang":"en","author":null,"publisher":"Facebook Watch","image":{"url":"https://cs.atdmt.com/event?t=FB+Public+Story+Page+Visit"},"date":"2019-10-13T23:39:47.000Z","logo":{"url":"https://static.xx.fbcdn.net/rsrc.php/yo/r/iRmz9lCMBD2.ico"},"url":"https://www.facebook.com/LaBioguia/videos/519973161895637/"},"status":"success"}
`

The  image is incorrect!!

Regards!!
