### ISSUE TITLE
Add a timeout?

### ISSUE THREAD

**Issue by apelsinet** [microlinkhq/metascraper#22]
It would be nice if you could specify a timeout and reject the returning promise after said timeout.

**Comment by thisbejim** [comment]
This would be a great addition.

**Comment by Kikobeats** [comment]
Hello,

I'm going to close that because new [2.0.0](https://github.com/microlinkhq/metascraper/issues/40) version doesn't handle with HTTP anymore, just need to provide the HTML 😄
