### ISSUE TITLE
issue url metadata

### ISSUE THREAD

**Issue by dverdugo85** [microlinkhq/metascraper#220]
### Prerequisites

- [5.7.6 ] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Subject of the issue

I try with https://api.microlink.io/?url=https://www.facebook.com/LaBioguia/videos/519973161895637/

show this:

{"data":{"title":"Un bocadito más y mañana arranco la dieta...","description":"Un bocadito más y mañana arranco la dieta...\nCréditos: IG @cruzysuzy","lang":"en","author":null,"publisher":"Facebook Watch","image":{"url":"https://cs.atdmt.com/event?t=FB+Public+Story+Page+Visit"},"date":"2019-10-13T23:39:47.000Z","logo":{"url":"https://static.xx.fbcdn.net/rsrc.php/yo/r/iRmz9lCMBD2.ico"},"url":"https://www.facebook.com/LaBioguia/videos/519973161895637/"},"status":"success"}

The image is incorrect!!

When change the order of wrap 
```
image: [
    wrap(
```

in the library that work 
Regards!!
Describe your issue here.

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
Can you make a PR?

**Comment by dverdugo85** [comment]
Yes of course I have also been working on a module to extract the url amp

**Comment by dverdugo85** [comment]
next week I could see that ... right now I have to deliver a project and I'm without much time

**Comment by Kikobeats** [comment]
no rush! just take your time 🙂

**Comment by Kikobeats** [comment]
@dverdugo85 I'm happy to accept a PR when you find time for moving this forward 👍

**Comment by dverdugo85** [comment]
Excuse me for not answering before ... I was hospitalized  and just came back to my house a few days ago
