### ISSUE TITLE
Add `iframe` property

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/metascraper#227]
Create a `metascraper-iframe` package that returns a new `iframe` property.

**Providers**

- [x] YouTube
- [x] Vimeo
- [x] Spotify
- [x] Twitter
- [x] Instagram
- [x] Facebook
- [x] SoundCloud
- [ ] Google Maps
- [x] Twitch
- [ ] Wikipedia
- [ ] GitHub Gist
- [ ] [moar providers](https://github.com/discourse/onebox/tree/e898a89e4d489cbec282ef47a55c917059c47301/spec/lib/onebox/engine)

_Anything else?_

**Inspiration**

- https://github.com/discourse/onebox ⭐
- https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-oembed.php
- https://github.com/mkopit/url-embed
- https://github.com/nodeca/embedza
- https://github.com/alanshaw/embed-video
- https://github.com/ritz078/embed-js
- https://github.com/abhaytalreja/react-social-embed
- https://github.com/shobhitsharma/embedo

**Related**

- https://blog.embed.ly/native-embeds-e670ccd4602

**Comment by karliky** [comment]
👍
