### ISSUE TITLE
JSON-LD @graph parsing

### ISSUE THREAD

**Issue by wyattjoh** [microlinkhq/metascraper#233]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

JSON-LD parsing.

### Steps to reproduce

Attempt to scrape a page containing (the apparently valid) structured data outputted by the [Yoast SEO plugin](https://github.com/Yoast/wordpress-seo/blob/34cf8c33905415f4027505476f251bef81d79226/inc/class-wpseo-utils.php#L1211-L1215) which outputs the following form:

```js
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Article",
      // ...
    },
    {
      "@type": "WebPage",
      // ...
    },
  ]
}
```

Which as you notice, does not contain a root object, and instead includes a graph of related objects. Maybe it's my misunderstanding of the JSON-LD spec, but it seems difficult to understand what the _root_ node is when trying to parse it, so property extraction is not possible, or could be non-deterministic.

### Expected behaviour

I'd expect when trying to find `dateModified` for it to find a valid entry in the graph.

### Actual behaviour

It instead returns undefined.

**Comment by Kikobeats** [comment]
hum could be easy to consider `@graph` as root node if it exists
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/index.js#L223

but first I need to understand what's `@graph`. Why they are using it?

.cc @plaa
