### ISSUE TITLE
Enhance facebook preview

### ISSUE THREAD

**Issue by shimika** [microlinkhq/metascraper#238]
### Prerequisites

- [ v ] I'm using the last version.
- [ v ] My node version is the same as declared as `package.json`.

### Subject of the issue

Twitter recommend to use
```html
<meta name="twitter:image" content="https://~~">
```
But facebook video preview page uses
```html
<meta property="twitter:image" content="https://~~">
```

metascraper-image only takes this one so cannot parse video preview
```javascript
$('meta[name="twitter:image"]').attr('content')
```

I think it is facebook's mistake but facebook would not fix it.
I just suggest to enhance this library's parseing coverage.
Maybe twitter:title, twitter:description also use property except name

### Steps to reproduce

Just open chrome secret tab and go to this [Link](https://www.facebook.com/gmoneycambodia/videos/284008875784842)

### Expected behaviour

Try to parse 
```html
<meta property="twitter:image" content="https://~~">
```

### Actual behaviour

Do not parse 
```html
<meta property="twitter:image" content="https://~~">
```

**Comment by Kikobeats** [comment]
This is clearly a wrong thing under Facebook HTML markup.

The solution there could create a specific metascraper bundles rules for Facebook urls, similar to
https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-uol

Maybe can you create a PR? 🙂

**Comment by Kikobeats** [comment]
ops, this is already reported! see #134

closing this in favour #134
