### ISSUE TITLE
image url return wihout https

### ISSUE THREAD

**Issue by jsappme** [microlinkhq/metascraper#24]
sometimes the meta image returns something like "//images.solecollector.com/complex/images/w_1200/viukziox1lihfkmhn2i5/off-white-air-jordan-1"

instead of "https://images.solecollector.com/complex/images/w_1200/viukziox1lihfkmhn2i5/off-white-air-jordan-1"

**Comment by NullVoxPopuli** [comment]
that just means it'll use whatever protocol your using?

**Comment by Kikobeats** [comment]
Closing that because [2.0.0](https://github.com/microlinkhq/metascraper/issues/40) iteration remove HTTP layer 😄
