### ISSUE TITLE
`truncateLength` ignored in metascraper-description

### ISSUE THREAD

**Issue by danikenan** [microlinkhq/metascraper#249]
### Prerequisites

- [x ] I'm using the last version.
- [ x] My node version is the same as declared as `package.json`.

### Subject of the issue

`truncateLength` ignored in metascraper-description

### Steps to reproduce

```
const metascraper = require('metascraper')([
  require('metascraper-description')({ truncateLength: 20000 }),
]);
metascraper({html: htmlWithLongerThan300CharsDescription, url});
```

### Expected behaviour

Description returned should not be truncated.

### Actual behaviour

Description is truncated.

**Comment by Kikobeats** [comment]
Thanks for reportings, look like parameters haven't been passed down properly, let me create a PR 🙂
