### ISSUE TITLE
iframe metadata should not be escaped

### ISSUE THREAD

**Issue by ckeeney** [microlinkhq/metascraper#251]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

`metascraper-iframe` is returning HTML-escaped HTML code. I'm aware of the [hackerone report](https://hackerone.com/reports/309367) regarding XSS vulnerabilities, but the iframe provider is specifically designed to return HTML code.

Further, I'd argue that `metascraper` shouldn't be sanitizing any metadata at all.  Data is being sanitized specifically for display in HTML, but that's not the only use case for consuming this library. By sanitizing the data inside the scraping library, you make it more complex or computationally expensive for any consumers of this library to use the raw metadata. Developers need to be responsible for sanitizing their untrusted data for whatever platforms they are targeting.

I do think if sanitation is removed from this library, a fairly strong warning should appear in the docs.

### Steps to reproduce

[runkit demonstrating the issue](https://runkit.com/ckeeney/5e09020b6e46ae001b8cfac5)

**Comment by Kikobeats** [comment]
I agree and that's why you can disable XSS behavior passing `{escape: false}`

I prefer don't have specific logic for just disabling this behavior on metascraper-iframe.

Thoughts?

**Comment by ckeeney** [comment]
Is it possible to have `{escape: false`} just for the iframe rule bundle?

Personally, I don't think `metadata` should do any escaping, and should instead return raw data.  I think escaping is best done closer to when metadata is rendered in the browser rather than when it is scraped.

Sanitizing all the metadata is adding overhead and code complexity, but there is no reason to assume that the scraped metadata is intended for display in a web browser.

I'd like to hear what the rest of the community thinks about this, but if it is already firmly decided that `metascraper` should perform XSS sanitation, then we can just close this issue because the `{escape: true}` option will solve my specific problem.

**Comment by Kikobeats** [comment]
I bet for removing `escape: true` since it's a thing you can do after extract the data using metascraper

**Comment by Kikobeats** [comment]
Released at `v5.9.0` 👍
