### ISSUE TITLE
Typescript .d.ts needed

### ISSUE THREAD

**Issue by pravin-d** [microlinkhq/metascraper#269]
Is there a plan on adding type definition files for this and other related rules packages ?

**Comment by Kikobeats** [comment]
not really, check https://github.com/microlinkhq/metascraper/issues/195

Happy to accept a PR for that!

**Comment by JbIPS** [comment]
Hello @pravin-d, just to let you know, the typings are here!

I'm not sure they're exhaustive so feel free to complete them if I miss something :wink:
