### ISSUE TITLE
Feature request to scrape twitter:site, twitter:description..etc

### ISSUE THREAD

**Issue by oneshot-engineering** [microlinkhq/metascraper#270]
### Prerequisites

- [Y ] I'm using the last version.
- [Y ] My node version is the same as declared as `package.json`.

### Subject of the issue
Not really bug but more of feature request to scrape twitter meta tags

Describe your issue here.
Feature request to scrape twitter:site, twitter:description..etc

### Steps to reproduce
N/A

### Expected behaviour
N/A

### Actual behaviour
N/A

**Comment by Kikobeats** [comment]
twitter meta tags are present when you use [title](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-title/index.js#L10), [description](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-description/index.js#L12), etc packages.

So just use these packages, and they will resolve twitter metatags when needed 🙂
