### ISSUE TITLE
[metascraper-readability] Extract more data

### ISSUE THREAD

**Issue by lqmanh** [microlinkhq/metascraper#278]
### Subject of the issue

[Readability](https://github.com/mozilla/readability) can extract:

* `content`: HTML string of processed article content
* `length`: length of an article, in characters
* `excerpt`: article description, or short excerpt from the content
* `byline`: author metadata
* `dir`: content direction

Thus, I believe metascraper-readability can, and should extract all those data.

### Expected behaviour

metascraper-readability should extract content, length and dir too.

### Actual behaviour

Now metascraper-readability only extracts title, description/excerpt, author/byline and publisher.

P/S: If you need some help, I can open a PR for this feature.

**Comment by Kikobeats** [comment]
can you explain a bit your use case? just to understand why you need that value.

The point of `metascraper-readability` is to map values to a set of normalized values (title, description, author,...) that's why the value you mentioned are skipped.

**Comment by lqmanh** [comment]
Oh I just want my scraper to be able to get article content without further manual intervention, so that I can do some post-processing like summarization, keyword extraction,...

**Comment by Kikobeats** [comment]
why not you just use readability?

**Comment by lqmanh** [comment]
Because I still need metascraper for other information, for various kinds of websites too.
Yes, I can use Readability directly, but there is already metascraper-readability here.
I can also roll out my own custom rule, but I thought this being supported in the mainstream might be a good idea, so I created this issue.
