### ISSUE TITLE
[metascraper-logo-favicon] option to specify selector preference

### ISSUE THREAD

**Issue by JS1010111** [microlinkhq/metascraper#279]
It would be useful to be able to specify for instance that apple-touch-icon has preference / should be used instead of others if it's available.

Not sure how to implement that using your patterns (opts, rules, etc) so this is a feature request.

Thanks

**Comment by Kikobeats** [comment]
Hello,

Can you provide a code snippet of your expectation of this option? just to be sure to understand how flexible you expect for this.

options can be passed as an object argument:

```js
const getLogo = require('metascraper-logo-favicon')({
  touchIcon: true
})
```

**Comment by JS1010111** [comment]
Hello,

Thanks for replying!

My use case is to get the apple-touch-icon and fallback to the default behavior of getting the biggest icon if there's no apple-touch-icon available.

So the following option would be perfect:

```js
const getLogo = require('metascraper-logo-favicon')({
  prefersAppleTouchIcon: true
})
```

I did a hack locally (without the options object) just to test my use case as below:

```js
'use strict'

const {
  absoluteUrl,
  logo,
  url: urlFn,
  toRule
} = require('@metascraper/helpers')

const { flow, first, toNumber, split, chain, concat } = require('lodash')
const { URL } = require('url')
const got = require('got')

const getSize = flow([str => split(str, 'x'), first, toNumber])

const getDomNodeSizes = (domNodes, attr) =>
  chain(domNodes)
    .map(({ attribs }) => ({
      size: getSize(attribs.sizes),
      link: attribs[attr],
      rel: attribs.rel ? attribs.rel : "" // ----- added this
    }))
    .value()

const getSizes = ($, collection) =>
  chain(collection)
    .reduce((acc, { tag, attr }) => {
      const domNodes = $(tag).get()
      const selectors = getDomNodeSizes(domNodes, attr)
      return concat(acc, selectors)
    }, [])
    .sortBy(({ size }) => -size)
    .value()

const sizeSelectors = [
  { tag: 'link[rel*="apple-touch-icon"]', attr: 'href' },
  { tag: 'meta[name*="msapplication-tileimage" i]', attr: 'content' },
  { tag: 'link[rel="icon"]', attr: 'href' },
  { tag: 'link[rel="shortcut icon"]', attr: 'href' }
]

const toUrl = toRule(urlFn)

const DEFAULT_GOT_OPTS = {
  timeout: 3000
}

/**
 * Rules.
 */
module.exports = ({ gotOpts } = {}) => ({
  logo: [
    toUrl($ => {
      const sizes = getSizes($, sizeSelectors)
      const appleTouchIcon = sizes.filter(s => s.rel === 'apple-touch-icon') // ----- added this
      if appleTouchIcon.length > 0 return appleTouchIcon.first() // ----- added this
      const size = chain(sizes)
        .first()
        .get('link')
        .value()
      return size
    }),
    async ({ url }) => {
      const logoUrl = absoluteUrl(new URL(url).origin, 'favicon.ico')
      try {
        await got.head(logoUrl, {
          ...DEFAULT_GOT_OPTS,
          ...gotOpts
        })
        return logo(logoUrl)
      } catch (err) {
        return null
      }
    }
  ]
})

```

**Comment by Kikobeats** [comment]
gotcha 🙂

The current logic is sorting the available favicon's by size.

Why you want `apple-touch-icon`? just curious 🙂

maybe the thing that can be exposed could be the [sort function](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-logo-favicon/index.js#L31)

**Comment by JS1010111** [comment]
Many sites have specific versions of their icons for the Apple platforms.
I'm developing an iOS app and I want it to be visually consistent with the OS, so the user sees the same icon in the app as in Safari Favorites for example.

To illustrate, theverge.com has it's icons customized:

https://cdn.vox-cdn.com/uploads/chorus_asset/file/7395351/android-chrome-192x192.0.png
![image](https://user-images.githubusercontent.com/10931029/84605835-dddf6300-ae76-11ea-9585-b6530dfc853c.png)

https://cdn.vox-cdn.com/uploads/chorus_asset/file/7395359/ios-icon.0.png
![image](https://user-images.githubusercontent.com/10931029/84605839-e9328e80-ae76-11ea-9ba1-a4841a18060f.png)

I'm not a professional developer and my experience with JS is just ok, so I'll let the "how" of implementation with you 😄

Thanks again! I really appreciate it!

**Comment by Kikobeats** [comment]
@JS1010111 

I refactored the implementation and now it's exposing [`pickFn`](https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-logo-favicon#pickfn) that you can use for achieving that:

```js
const pickFn = (sizes, pickDefault) => {
  const appleTouchIcon = sizes.find((item) => item.rel.includes('apple'))
  return appleTouchIcon || pickDefault(sizes)
}

const metascraper = require('metascraper')([
  require('metascraper-logo-favicon')({
    pickFn
  })
])
```

**Comment by JS1010111** [comment]
Thanks a lot Kiko! Looks awesome!
