### ISSUE TITLE
Custom nested rules

### ISSUE THREAD

**Issue by luminous8** [microlinkhq/metascraper#286]
I cannot find it in the [documentation](https://metascraper.js.org/#/CONTRIBUTING?id=writing-your-own-rules), but I'm curious to know if it's possible to have nested rule like this 👍 

author : {
avatar: ({ htmlDom: $, url }) => $('.avatar').attr('src'),
urlProfile: ({ htmlDom: $, url }) => $('.link').attr('src'),
...
}

so at the end we can get the data well organised?

Thanks

**Comment by Kikobeats** [comment]
it isn't a thing supported but the core, but you can create your own rules set and expose the data in that way 🙂

**Comment by luminous8** [comment]
How can I do that?
When I something like this, it doesn't work

`
const rules = {
    truc: {
      author: [
        ({ htmlDom: $, url }) =>
          $(".slat-header.user .shot-byline-user > a").text(),
      ],
    },
}
`
