### ISSUE TITLE
Issue with re2 binary on alpine image

### ISSUE THREAD

**Issue by trueter** [microlinkhq/metascraper#303]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

On my mac everything works fine, but in our node:12.14-alpine image, the following stack trace prevents the app from starting:
```
throw err;
^
Error: Cannot find module './build/Release/re2'
Require stack:
- /usr/src/app/node_modules/re2/re2.js
- /usr/src/app/node_modules/url-regex-safe/lib/index.js
- /usr/src/app/node_modules/@metascraper/helpers/index.js
- /usr/src/app/node_modules/metascraper/src/index.js
- /usr/src/app/meta-parser.js
```

### Workaround

By downgrading to `5.14.3` I was able to avoid the issue. 

Leaving this preliminary info here in case anyone else needs to circumvent the issue until the issue is better understood.

**Comment by Kikobeats** [comment]
hum strange, I have a docker image using node13 and it works fine.

Can you try to use node13 instead?

**Comment by franky47** [comment]
I just had the same issue, I solved it by reinstalling dependencies with the `--no-ignore-scripts` flag in Yarn, which builds the missing re2 module at install time.
