### ISSUE TITLE
Can't resolve iso-639-3/to-1 in @metascraper/helpers

### ISSUE THREAD

**Issue by drpiou** [microlinkhq/metascraper#304]
### Prerequisites

- I'm using the last version.
- My node version is 14.4.0.

### Subject of the issue

I cannot transpile because of `const langs = Object.values(require('iso-639-3/to-1'))` import into `@metascraper/helpers/index.js`.

### Steps to reproduce

Maybe this is related to my Babel configuration, but I don't know how to reproduce this error...

### Expected behaviour

It should transpile without any error.

### Actual behaviour

It doesn't transpile, I get this error:
```
ERROR in ./node_modules/@metascraper/helpers/index.js
Module not found: Error: Can't resolve 'iso-639-3/to-1' in '/Users/alex/Development/Web/xxx/node_modules/@metascraper/helpers'
 @ ./node_modules/@metascraper/helpers/index.js 26:28-53
 @ ./node_modules/metascraper/src/index.js
 @ ./assets/src/web/js/layouts/pages/Dashboard/ArticleDetails/Content/Builder/EmbedLink/index.js
 @ ./assets/src/web/js/layouts/pages/Dashboard/ArticleDetails/Content/Builder/index.js
 @ ./assets/src/web/js/layouts/pages/Dashboard/ArticleDetails/Content/index.js
 @ ./assets/src/web/js/layouts/pages/Dashboard/ArticleDetails/index.js
 @ ./assets/src/web/js/index.js
 @ multi ./assets/src/web/js/index.js ./assets/src/web/css/index.scss
```

### Fix purposal

Change `const langs = Object.values(require('iso-639-3/to-1'))` import to `const langs = Object.values(require('iso-639-3/to-1.json'))` into `@metascraper/helpers/index.js`.

**Comment by Kikobeats** [comment]
@drpiou can you convert this into a PR? 🙂

**Comment by Kikobeats** [comment]
I think you need to configure your babel to handle json files properly
