### ISSUE TITLE
Running on lambda

### ISSUE THREAD

**Issue by marcelinhov2** [microlinkhq/metascraper#306]
### Prerequisites

- [X] I'm using the last version.
- [X] My node version is the same as declared as `package.json`.

### Subject of the issue

When I try to run the code in lambda I got this error

![image](https://user-images.githubusercontent.com/232648/93426569-ad063400-f892-11ea-8711-00dab49ce54f.png)

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
You need to use node 12.x

**Comment by marcelinhov2** [comment]
I'm using it already.

**Comment by marcelinhov2** [comment]
![image](https://user-images.githubusercontent.com/232648/93486078-25dcae80-f8da-11ea-8745-67998730db7b.png)

**Comment by Kikobeats** [comment]
ops, I checked and [https://api.microlink.io](api.microlink.io) are using Node.js v13, so I guess re2 binary for Node 12.x is failing.

Try inspecting re2 projects issues 🙂

**Comment by fnmendez** [comment]
Getting same error, any update on this?

**Comment by fnmendez** [comment]
I'm new to Docker but I managed to build properly for AWS Lambda environment using it.

In my project root I made this Dockerfile:

```
# Dockerfile

# https://github.com/lambci/docker-lambda is a docker image that "almost replicates lambda environment"
FROM lambci/lambda:build-nodejs12.x

COPY . .

RUN npm install -g yarn

RUN rm -rf node_modules && rm yarn.lock
# maybe remove more environment specific built files?

RUN yarn install
# maybe run more config build commands?
```

I build the Docker image with
`docker build -t lambda-deploy .`

Then I run it setting some env vars on runtime that I need for deployment, and running bash on it so I can check everything is OK and deploy manually

`docker run -e AWS_ACCESS_KEY_ID=xxx -e AWS_SECRET_ACCESS_KEY=yyy -e SERVERLESS_ACCESS_KEY=zzz -it lambda-deploy /bin/bash`
