### ISSUE TITLE
Sets of selectors or non-combinatorial data

### ISSUE THREAD

**Issue by aaronhesse** [microlinkhq/metascraper#309]
I'm using metascraper in a project I'm working on. I'm passing in custom rules into the contructor. It's actually scraping actual content from the page its scraping. The problem is, is that it appears to be finding every tag that matches the CSS selector, and combining all of the text() content from every tag on the page. I checked metascraper website and github and couldn't find any information about an option that changes this kind of mode/behavior. I made sure that each scrape request creates a new instance of metascraper in case it was just using the same member variables across multiple uses of the object, but that didn't seem to do anything.

Ideally I'd use metascraper to scrape as many sets of selectors as possible. This project is a webcrawler that finds review information on amazon product pages. I want to be able to select a set of 4 selectors content, and then 4 more, and then 4 more, until there's no first-selector found on the page. For example: ["review title", "review author", "review text", "review rating"]. Process these 4 selector searches in a group, then repeat the group of css selectors again and again until it can no longer find another "review title" css selector, and then return an array of arrays of all the data.

Sorry if this is not an issue, I'm not sure where else to post this, and already posted on stackoverflow, with no answers.

Any thoughts?

**Comment by Kikobeats** [comment]
Hello, I think you need to create your own custom rules and delegate into [cheerio API](https://github.com/cheeriojs/cheerio) for creating that blocks of content

Just for illustrating, this is a way we use for trying to maximize logo detection using favicon markup
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-logo-favicon/index.js#L48

as you can see we declare the interested selectors and after that, we iterate over the DOM for getting what we want.

so I think in your case is going to be pretty similar, take a look and tell me 🙂
