### ISSUE TITLE
Update cheerio to 1.0.0-rc.2

### ISSUE THREAD

**Issue by AfzalivE** [microlinkhq/metascraper#31]
Getting this error:

```
ERROR in ./node_modules/cheerio/index.js
Module not found: Error: Can't resolve './package' in '....../node_modules/cheerio'
```

**Comment by blakeembrey** [comment]
Is this from Webpack? Make sure you're resolving `.json` files.

**Comment by Kikobeats** [comment]
Hello,

I'm going to close this because new [2.0.0](https://github.com/microlinkhq/metascraper/issues/40) iteration will be shipped with dependencies updated 😄
