### ISSUE TITLE
[metascraper-ffta] creation of a new metascraper

### ISSUE THREAD

**Issue by SylvainSimplonGit** [microlinkhq/metascraper#311]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Need an example

I'm trying to scrape view-source: [ffta/epreuves](view-source:https://www.ffta.fr/ws/epreuves?ChxDiscipline=S&ChxTypeChampionnat=&ChxLigue=CR09&ChxDepartement=&ChxClub=&ChxDateDebut=2020-09-01&ChxDateFin=2021-03-31) to retrieve all "EprvNumero"
I manage to recover the first one but not the whole

### The rules

to get the first :
`({ htmlDom: $, url }) => $('span[class="eprv-state eprv-state-A"]').attr('title')`

to get all :
`({ htmlDom: $, url }) => $('span[class="eprv-state eprv-state-A"]').get()`

How I can retrieve all occurrences ?
An example will help me a lot
Thanks a lot for your answers

**Comment by Kikobeats** [comment]
That's a cheerio API question rather than metascraper!

https://stackoverflow.com/a/54816526
