### ISSUE TITLE
Fallback rules cause an exception "rule is not a function"

### ISSUE THREAD

**Issue by jimlesch** [microlinkhq/metascraper#32]
This particular scenario throws an exception:
const MY_RULES = {
  title: [
    myPreferredTitleRule,
    myFallbackTitleRule,
    mySuperLastResortTitleRule,
  ]
}
scrapeMetadatum does not seem to anticipate receiving fallback rules and throws an exception on line 95: var next = rule($, url); when "rule" is an array of functions instead of a function itself.

**Comment by Kikobeats** [comment]
I'm going to close that because in v2 iteration rules are not exposed
