### ISSUE TITLE
Unable to generate re2 binary

### ISSUE THREAD

**Issue by Amenacliff** [microlinkhq/metascraper#330]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Describe your issue here.

### Steps to reproduce
Just install the package and start your server

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

### Expected behaviour
No error code

Tell us what should happen

Should run smoothly

### Actual behaviour

Tell us what happens instead

I get this : 
![image](https://user-images.githubusercontent.com/47929647/101242973-48be7800-36fd-11eb-8fdf-47e83112ab4f.png)

**Comment by Kikobeats** [comment]
Hello,

unfortunately, there is nothing I can't do there

can you report the bug at [re2 repository](https://github.com/uhop/node-re2/issues/64)?

**Comment by jaredscheib** [comment]
@Amenacliff this one may be related to https://github.com/microlinkhq/metascraper/issues/303, which just helped us.

**Comment by Amenacliff** [comment]
@jaredscheib  Thanks I'll check that
