### ISSUE TITLE
Example on parsing AMP jsonld for Recipe type

### ISSUE THREAD

**Issue by StErMi** [microlinkhq/metascraper#331]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

I would like to create a plugin to scrape AMP Recipe objects. 

Question 1: Which should be the correct format?
As far as I get I should return single attributes and not a whole object, right?

so something like

```
{
    estimatedCost: "something",
    prepTime: "something"
}
```

and not 

```
{
    recipe: {
        estimatedCost: "something",
        prepTime: "something"
    }
}
```

Question 2: How should I parse arrays?

if I try to parse ingredients like 

```
recipeIngredient: [
        ({ htmlDom: $, url }) => $jsonld('recipeIngredient')($,url),
]
```

I get a `string` and not an `array of strings` as I would like

**Comment by Kikobeats** [comment]
Hey,

Take a look at https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-telegram/index.js#L50

`$jsonld` returns just one result, if if you want to get an array as output, just wrap the result into an array 🙂

**Comment by StErMi** [comment]
@Kikobeats hi, maybe I dind't get it right. 

The issue about the array is that even if the information is a JSON array when I do `$jsonld('recipeIngredient')($,url)` it will return a `string` with all the results joined by `,`. Would it be possible to return the parsed array?

**Comment by Kikobeats** [comment]
humm try to use [jsonld](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/index.js#L262) helper instead and pick the value from the result

**Comment by StErMi** [comment]
Hi @Kikobeats could you give me an example of doing that? I think that the problem is that you transform everything into a string

**Comment by Kikobeats** [comment]
See the tests
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/test/index.js#L186

It returns an array!
