### ISSUE TITLE
Error: Can't walk dependency graph: Cannot find module 'metascraper-image'

### ISSUE THREAD

**Issue by erik-valtechsd** [microlinkhq/metascraper#332]
### Prerequisites

- [x ] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Subject of the issue

Using your example instructions on your README - I installed via metascraper npm and add the rules i need:
`const metascraper = require("metascraper")([
  require("metascraper-image")(),
  require("metascraper-title")(),
  require("metascraper-url")(),
]);
const got = require("got");
`

only to get `Error: Can't walk dependency graph: Cannot find module 'metascraper-image'` when i run it?

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
You need to perform an npm install

**Comment by erik-valtechsd** [comment]
Of course I npm installed metascraper as per the readme. Are you saying I have to install each of the dependencies I want also? `npm i metascraper-image` etc?

**Comment by Kikobeats** [comment]
exactly 🙂

A PR improving docs are very welcome!
