### ISSUE TITLE
[metascraper-audio] Pull mp3 files from a tag href

### ISSUE THREAD

**Issue by goleary** [microlinkhq/metascraper#338]
Hey @Kikobeats!
To pick  up our crisp convo:

I'm curious if you would accept a PR to this effect on the audio package:

```diff
module.exports = () => ({
  audio: [
    toAudio(($) => $('meta[property="og:audio:secure_url"]').attr("content")),
    toAudio(($) => $('meta[property="og:audio"]').attr("content")),
    toAudio(($) => {
      const contentType = $(
        'meta[property="twitter:player:stream:content_type"]'
      ).attr("content");
      const streamUrl = $('meta[property="twitter:player:stream"]').attr(
        "content"
      );
      return contentType ? withContentType(streamUrl, contentType) : streamUrl;
    }),
    toAudio(($) => $("audio").attr("src")),
    toAudio(($) => $("audio > source").attr("src")),
+   toAudio(($) =>
+      $("a")
+        .filter((_, element) => /.mp3/.test(element.attribs["href"]))
+        .attr("href")),
    },
  ],
});
```

It manages to return the audio url for the instance that we discussed (https://www.npr.org/2020/12/30/951460511/bitcoin-losers-classic).  I've actually seen a number of sites include download links that would be captured by a technique like this. We could expand the regex to cover other file formats too.

**Comment by Kikobeats** [comment]
Hello, and sure thing!

Just I'm trying to figure the best implementation for that. Ideally, we can detect any browser-friendly audio extension

Maybe a better approach could be:

- extract the audio extension (https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/index.js#L181)
- check if it's an audio extension (https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-helpers/index.js#L73)

That should maximize the results 🙂

**Comment by goleary** [comment]
Great idea!

What about this?

```js
toAudio(($) =>
  $("a")
    .filter((_, element) =>
      isAudioExtension(extension(element.attribs["href"]))
    )
    .attr("href")

**Comment by Kikobeats** [comment]
for getting prerender HTML on demand, take a look to https://microlink.io/recipes/get-html 👍
