### ISSUE TITLE
Passing options to popsicle (e.g. headers)

### ISSUE THREAD

**Issue by Justin-Maxwell** [microlinkhq/metascraper#34]
We get unscrapable responses trying to access YouTube video .../watchv= URLs (via a cors-proxy).

Or rather, ten times out of eleven.  The content shown in browser dev tools (network) is almost all <script> and no meta tags.

In PostMan, if I clear the user-agent header, I get consistently usable data.  I want to try this for metascraper, but I can't see any way to tell it to use a popsicle instance with options (i.e. custom headers) specified.

Is there any way to override popsicle defaults for metascraper?  If not, it may make sense to be able to pass-through either a prebuilt popsicle object, or popsicle options.  Is there quick workaround to over-ride the user-agent header when using metascraper from a browser?

EDIT:

Probably pointless, unless an expert can advise otherwise.  Trying to set the user-agent header on popsicle just gives `Refused to set unsafe header "user-agent"` which is presumably enforced at the browser level.    I've been trying to hold off on implementing a custom back-end cors/scrape-proxy, but maybe that's the only option.

**Comment by mahnuh** [comment]
Hi @Justin-Maxwell,
I needed this as well to pass a custom header to popsicle, so I created this pull request: #38

**Comment by Kikobeats** [comment]
Hello,

I'm going to close this because [2.0.0] iteration will be not handled HTTP anymore!
