### ISSUE TITLE
metascraper-audio: No audio returned when src is .mpga

### ISSUE THREAD

**Issue by goleary** [microlinkhq/metascraper#345]
Here are a couple of examples:
https://talk-therapy.every.to/p/onstress
https://andrewsullivan.substack.com/p/brian-muraresku-on-psychedelics-and

They both have

```
<audio src="XXX.mpga" />
```

But metascraper seems not to recognize this as an audio type.

Chrome seems to support this filetype (verify [here](https://cdn.substack.com/public/audio/365ff8d0-6d25-4910-be28-952528495877.mpga?post_id=24870695)).

Looks like [this ](https://github.com/scrapjs/audio-extensions/blob/master/audioExtensions.json) may be a little out of date

**Comment by Kikobeats** [comment]
You're right, the audio extension is missing at `audio-extensions`, and looks like the package is unmaintained. Probably more supported audio extensions are missing at this point.

Let me ask openly @reqshark @dy if the repo can be transfer to github.com/microlinkhq and ownership assigned to `kikobeats` on npm, so Microlink would be the new maintainer there and keep it up to date again.

**Comment by goleary** [comment]
Great idea!

Let me know if there is anything I can do to help.

**Comment by Kikobeats** [comment]
this is interesting

> Using the .mpga extension is a non-standard way of denoting MP3 files and should generally be avoided. One particular case when the .mpga extension is extensively used relates to the Android OS on which it is auto-assigned to any downloaded MP3 file.

https://www.filetypeadvisor.com/extension/mpga

**Comment by goleary** [comment]
Interesting. I'm using [ExoPlayer](https://exoplayer.dev/) and it seems to have no trouble with the `.mpga` files I provide it.

Since we have no control over which extension sites use & it's basically just a mp3 file I still think it makes sense to support.

**Comment by Kikobeats** [comment]
shipped at `v5.16.14`, also at Microlink API

- https://api.microlink.io/?url=https://talk-therapy.every.to/p/onstress&audio
- https://api.microlink.io/?url=https://andrewsullivan.substack.com/p/brian-muraresku-on-psychedelics-and&audio

🎉

**Comment by goleary** [comment]
awesome, thanks @Kikobeats !!
