### ISSUE TITLE
[metascraper-author] wrong author name on Daily Beast article

### ISSUE THREAD

**Issue by jonpincus** [microlinkhq/metascraper#347]
### Prerequisites

- [X ] I'm using the last version.
- [X ] My node version is the same as declared as `package.json`.

### Subject of the issue

metascraper-author is picking up incorrect information about the author from a Daily Beast page at https://www.thedailybeast.com/pentagon-denied-request-to-give-covid-19-vaccine-to-national-guard-troops-before-inauguration

In the html

```<meta name="authors" content="Erin Banco">```

(instead of name="author")

Not sure where the incorrect information comes from, maybe some of the JSON-LD?

### Steps to reproduce

```
var author = require("metascraper-author");
var metascraper = require("metascraper")([author()]);
var fetch = require("node-fetch");
var url = "https://www.thedailybeast.com/pentagon-denied-request-to-give-covid-19-vaccine-to-national-guard-troops-before-inauguration";

fetch(url).then(res => res.text())
    .then(html => metascraper({url,html}))
    .then(result => console.log(result.author))
```

### Expected behaviour

It should output

Erin Banco 

### Actual behaviour

Actually outputs 

Coronavirus

**Comment by Kikobeats** [comment]
that's happening because `authors` is not a well-known valid meta tag.

The website should use [`author`](https://www.w3.org/TR/2017/REC-html52-20171214/document-metadata.html#author) instead!
