### ISSUE TITLE
Error trying to scrape http://facebook.com

### ISSUE THREAD

**Issue by lnmunhoz** [microlinkhq/metascraper#35]
This is the code in my express router:
```js
console.log('Scraping metadata...', req.query.url);
  Metascraper.scrapeUrl(req.query.url)
  .then((metadata) => {
    console.log(metadata);
    res.send(metadata);
  })
  .catch((err) => {
    console.log(err);
    res.send(err);
  });
```

It returns this error when trying to scrape http://facebook.com
```
{ [Error: incorrect header check] errno: -3, code: 'Z_DATA_ERROR' }
```

Any thoughts why this is happening?

**Comment by lnmunhoz** [comment]
Now its not working for other websites as well, and returning another error:

```
 { [Error: unknown compression method] errno: -3, code: 'Z_DATA_ERROR' }
```

I think this errors may be related to other dependencies of this lib...

**Comment by ayalpani** [comment]
I am experiencing the exact same problem with facebook and other sites. Any ideas?

**Comment by Kikobeats** [comment]
Closing that because [2.0.0](https://github.com/microlinkhq/metascraper/issues/40) iteration move HTTP calls out of the library, stay stunning!
