### ISSUE TITLE
"By" is incorrectly stripped from author name

### ISSUE THREAD

**Issue by hunterclarke** [microlinkhq/metascraper#352]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

When parsing articles by the author "Byrne Hobart," the "By" is stripped from the beginning.

### Steps to reproduce

1. Run metascraper-author over https://diff.substack.com/p/how-bubbles-and-megaprojects-parallelize

### Expected behaviour

`author` should be "Byrne Hobart"

### Actual behaviour

`author` is "rne Hobart"

**Comment by Kikobeats** [comment]
fixed at metascraper@5.16.16

can you confirm now is working fine?

**Comment by hunterclarke** [comment]
Works great @Kikobeats. Thanks!
