### ISSUE TITLE
[metascraper-audio] Run parser on subframes of page

### ISSUE THREAD

**Issue by goleary** [microlinkhq/metascraper#356]
I've noticed a variety of websites where  the audio URL lives in an iframe and within that iframe the URL follows a format that metascraper understands.

Here are a few examples (link, followed by iframe url where metascraper succeeds & the rule that gets the job done):

https://www.indiehackers.com/podcast/032-peter-and-calvin-of-segment
https://share.transistor.fm/e/70c487ed (`a['href']`)

https://theflip.africa/podcast/digitizing-healthcare-helium-health-goke-olubusi/
https://player.simplecast.com/3ab2ec74-8d89-4344-9be0-a30fa53ac6a7 (`audio['src']`)

https://bfi.uchicago.edu/podcast/the-big-tech-threat/
http://wbez-rss.streamguys1.com/player/player21011316001810372.html (`audio['src']`)

If we were to apply the `metascraper-audio` rules to the contents of the iframe then we could successfully get the audio URLs.

I realize a solution may be relatively complex, so I'm presenting this to you @Kikobeats to see if you have any ideas about how we could achieve this.

Even when I present `metascraper` with an HTML string that contains the the dom of the document inside an `iframe` tag it seems to ignore everything inside of the `iframe` tag.

Seems like this might require running the parser on all frames in the page until something is returned?

**Comment by Kikobeats** [comment]
shipped at `v5.18.0`

Also available at Microlink API:

http://api.microlink.io/?url=https%3A%2F%2Fwww.indiehackers.com%2Fpodcast%2F032-peter-and-calvin-of-segment&audi
