### ISSUE TITLE
Image with params

### ISSUE THREAD

**Issue by Nicolas-PL** [microlinkhq/metascraper#362]
### Prerequisites

- [X] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`. => Node v14.8

### Subject of the issue

Hello, 

if my meta og:image have params in url the scraper doesn’t works.

### Steps to reproduce
Example : 

this doesn’t works (image = null) : 
`<meta property="og:image" content="https://localhost/v1/images/1754197/raw?width=900&height=600&fit=max&hash=57b6011c9a58304e3a3434d6f00f46e201a3c756" />  `

no problem with : 
`<meta property="og:image" content="https://localhost/v1/images/1754197" />`

Thank you for your help

**Comment by Kikobeats** [comment]
Hello,

That is happening because `raw` is detected as audio extension
