### ISSUE TITLE
URL and relative image URLs not working

### ISSUE THREAD

**Issue by mahnuh** [microlinkhq/metascraper#37]
Hi,

I set up a small test page (with nearly no metadata) to play around with metascraper and noticed two unexpected things:
1. image will be returned null if the only available <img> on the page has a relative URL (works fine with absolute URLs)
2. url is always null (both for the direct URL to the page and short URLs)

The test page can be found here: http://x.manuel-heidrich.com/tests/browse/
Short URLs for the test page: http://bit.ly/2zVanQ9 and https://goo.gl/gTYg35

HTML of the test page: http://sharedby.manuel-heidrich.com/Cs6cno/3QJaQeuE
Response from metascraper: http://sharedby.manuel-heidrich.com/WAH4q/1HE7KFYF

In case of the images I guess it would be great if in case of relative URLs imagescraper would return absolute URLs.

Concerning the URL: Is it a bug or intended behaviour? I think url should never be null.

Happy to help if I can!

**Comment by Kikobeats** [comment]
Hey,

on v2 I added a method to always be sure url is absolute:
https://github.com/microlinkhq/metascraper/blob/v2/src/util.js#L12

so we can close that 😄
