### ISSUE TITLE
[metascraper-date] hangs on page with datelike string and lots of spaces

### ISSUE THREAD

**Issue by jonpincus** [microlinkhq/metascraper#378]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

metascraper-date hangs, due to [a bug in chrono-node](https://github.com/wanasit/chrono/issues/382).

(metascraper-date is currently using a slightly old version of chrono-node, but I verified that the problem still occurs using the current chrono-node version 2.2.2)

### Steps to reproduce

```
var date = require("metascraper-date");
var metascraper = require("metascraper")([date()]);
var fetch = require("node-fetch");
var url = "http://bgreunion.co.uk/BGR3/";

fetch(url).then(res => res.text())
    .then(html => (console.log("running html"), metascraper({url,html})))
    .then(result => console.log("date is", result.date))
```

### Expected behaviour

Should print out the date.

### Actual behaviour

Call to metascraper never returns.

**Comment by Kikobeats** [comment]
@jonpincus do you know what's the latest `chrone-node` version works as expected?

I can downgrade the dependency until the issue will be resolved

**Comment by Kikobeats** [comment]
closing since the original issue is closed and dependency is upgraded.
