### ISSUE TITLE
TypeError: Cannot read property 'parent' of null

### ISSUE THREAD

**Issue by lchangdev** [microlinkhq/metascraper#39]
trying to run the basic example however it is logging `TypeError: Cannot read property 'parent' of null`

```
    import Metascraper from 'metascraper';

    Metascraper
      .scrapeUrl('http://www.bloomberg.com/news/articles/2016-05-24/as-zenefits-stumbles-gusto-goes-head-on-by-selling-insurance')
      .then((metadata) => {
        console.log('meta: ', metadata);
      })
      .catch((error) => {
        console.log('error: ', error);
      });
```

**Comment by mahnuh** [comment]
Hi @lchangdev,

unfortunately I am not able to reproduce this error. Can you please provide a repo or a zip file with code that is not working for you?

**Comment by Kikobeats** [comment]
Closed because non reproducible, I added a github issue template for the next time
