### ISSUE TITLE
[metascraper-twitter] Correct Images are Not Getting Scraped from Twitter

### ISSUE THREAD

**Issue by Siddhant-K-code** [microlinkhq/metascraper#397]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

https://api.microlink.io/?url=https://twitter.com/elninoict/status/1106176415622418433
it is only returning the user logo image and not returning the post image

### Steps to reproduce

Just Go To Above URL 

### Expected behavior

Returning the Post Image Link/URL

### Actual behavior

Returning User Profile Image Link/URL

**Comment by Kikobeats** [comment]
Thanks for reporting; A specific `metascraper-twitter` should be created to handle this.

**Comment by Kikobeats** [comment]
close in favour of #260; lets continue the conversation there 🙂
