### ISSUE TITLE
Error during Require of Metascraper

### ISSUE THREAD

**Issue by ryankashi** [microlinkhq/metascraper#399]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

When trying to require Metascraper, I get the following error:
`electron/js2c/asar.js:140 Uncaught Error: The module '\\?\C:\path\to\my\application\node_modules\re2\build\Release\re2.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).`

### Steps to reproduce

Install the latest stable release of Node.js from the website:
https://nodejs.org/en/

Then install metascraper using npm

Tell us how to reproduce this issue.

### Expected behaviour

The require statement as described in the example code works as expected. Is there an exact known stable version of Node that metascraper works on? I have tried both the stable version of Node 12.x (NODE_MODULE_VERSION 72) as well as Node 14.x (NODE_MODULE_VERSION 83).

I cannot find a NODE_MODULE_VERSION of nodejs based on the following archive:
https://nodejs.org/en/download/releases/

### Actual behaviour

The require statement results in the above error.

**Comment by Kikobeats** [comment]
hello, that's happening because you performed an `npm install` using a node version that is different than the node version used for running your application.

To fix it: remove `node_modules` and perform `npm install` again!

**Comment by ryankashi** [comment]
After a bit of digging, it appears that this does not quite solve the issue and it appears to be a non-trivial issue.

I am currently building for an Electron application, in which case suggests to do the following:

https://www.electronjs.org/docs/tutorial/using-native-node-modules

`Error: The module '/path/to/native/module.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION $XYZ. This version of Node.js requires
NODE_MODULE_VERSION $ABC. Please try re-compiling or re-installing
the module (for instance, using 'npm rebuild' or 'npm install').`

As I have been using electron-forge for my application, it turns out that this process has been handled under the hood the entire time, and that one of the packages associated with metascraper fails to be rebuilt (potentially re2?).

The troubleshooting steps are successful for all other packages except for when metascraper is applied to my dependencies, at which case rebuilding for Electron results in the failure for the Metascraper package or its associated dependencies. The error I receive is:

`Error: node-gyp failed to rebuild 'C:\path\to\my\project\node_modules\re2'.`

    at ModuleRebuilder.rebuildNodeGypModule (C:\path\to\my\project\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at async Rebuilder.rebuildModuleAt (C:\path\to\my\project\node_modules\electron-rebuild\lib\src\rebuild.js:190:9)
    at async Rebuilder.rebuild (C:\path\to\my\project\node_modules\electron-rebuild\lib\src\rebuild.js:152:17)
    at async C:\path\to\my\project\node_modules\electron-rebuild\lib\src\cli.js:146:9

Requesting that this issue be reinvestigated as this error is no longer trivial to fix and is unique for metascraper and its associated dependencies. I have also tried matching my exact Node version to the one used by the exact version of electron, however this does not work either (although this was expected as described per Electron's linked docs)

**Comment by devrck** [comment]
On node 16 it fails.

**Comment by Rykuno** [comment]
Found this package but install is still failing it looks like

**Comment by Kikobeats** [comment]
Thanks for the investigation @ryankashi. 

Theoretically [r2 is now an optional dependency](https://github.com/niftylettuce/url-regex-safe/commit/a4189409286abf392b164ed9d662773dc42204af). Anyone can try the same problem to determine if is it still a thing?

Alternatively, I know its not ideal solution but you can consume the library via external request against [api.microlink.io](https://api.microlink.io)

**Comment by AndrewEQ** [comment]
Hi guys, tried installing Xcode dev tools, and its still not working again with the latest Electron, any other ideas as to why it can't rebuild re2?
