### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/metascraper#40]
We are working on a [v2](https://github.com/microlinkhq/metascraper/tree/v2) iteration.

## TODO

- [x] Close all issues related with HTTP problems.
- [x] Migrate documentation.
- [x] Update dependencies.
- [x] Migrate benchmark.
- [ ] Add contributor guidelines.

## Breaking Changes

The major breaking changes in this new version are that HTTP layers are moved out of the library.

From now, metascraper will be a main function that receives HTML and URL for extracting the data:

```js
const metascraper = require('metascraper')
const got = require('got')

const targetUrl = 'http://www.bloomberg.com/news/articles/2016-05-24/as-zenefits-stumbles-gusto-goes-head-on-by-selling-insurance'

;(async () => {
  const {body: html, url} = await got(targetUrl)
  const metadata = await metascraper({html, url})
  console.log(metadata)
})()
```

Because this iteration refactor a lot of code, is not possible create a PR, so I'm going to use this issue as a tracking list of things to close before release the new version.

## Improvements

- Add new [`logo`](https://github.com/microlinkhq/metascraper/blob/v2/src/get-data/rules/logo.js) field.
- Updated tests, now with at least top50 popular internet sites.
- The codebase was simplified and ready for supporting plugins in `3.0.0`.

**Comment by bkniffler** [comment]
Any example of how to use rules?

**Comment by Kikobeats** [comment]
@bkniffler hey, I opened a PR right now to define a way to extend rules, can you feedback me about that?

https://github.com/microlinkhq/metascraper/pull/41
