### ISSUE TITLE
Iam not getting metadata for youtube links

### ISSUE THREAD

**Issue by venkataramkrishna** [microlinkhq/metascraper#413]
### Prerequisites

- [x] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Subject of the issue

Describe your issue here.

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
Sorry but at least you need to provide a reproducible piece of code

**Comment by venkataramkrishna** [comment]
const metascraper = require('metascraper')([
    require('metascraper-author')(),
    require('metascraper-description')(),
    require('metascraper-image')(),
    require('metascraper-logo')(),
    require('metascraper-publisher')(),
    require('metascraper-title')(),
    require('metascraper-url')(),
    require('metascraper-youtube')()
  ])
   const targetUrl = req.body.url
  
  ;(async () => {
    const { body: html, url } = await got(targetUrl)
    const metadata = await metascraper({ html, url })
    res.send({'status':'success',data:metadata});
  })()
This is my code and iam using this api in loop mean continue caling the api when page loads its is not giving the metada for youtube urls


https://www.youtube.com/watch?v=ZKxhnrtj3DY
https://www.youtube.com/watch?v=ZKxhnrtj3DY
https://www.youtube.com/watch?v=xEOdVN16Qzg&t=9s
https://www.youtube.com/watch?v=ZKxhnrtj3DY
https://www.youtube.com/watch?v=MZTlzGoBUkY
https://www.youtube.com/watch?v=xEOdVN16Qzg&t=9s

these are some of urls

**Comment by Kikobeats** [comment]
if it works in your local system, then the issue is related to your production environment.

Also `metascraper-media-provider` package there:
https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-media-provider

**Comment by Kikobeats** [comment]
Hey, 

I wrote a blogpost explaining what's happening there:

https://microlink.io/blog/proxy-capabilities/
