### ISSUE TITLE
[metascraper-title] fetch <title> tag content?

### ISSUE THREAD

**Issue by alexpluto** [microlinkhq/metascraper#415]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Suggestion to include in the rules, the <title>content</title> tag for getting page title.

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

This is a link with bad markup: https://snowflakegelato.co.uk/

But, like most webpages, it does have: 

`<title>Snowflake Gelato | Luxury Gelato</title>`

### Expected behaviour

Can a rule be added to extract this if meta fields and other checks fail?

Has this been considered before and I am missing something?

### Actual behaviour

Pass <title> value back to request (if other rules fail)

**Comment by Kikobeats** [comment]
Hello,

The tag `<title />` is already included. It takes into consideration after social meta tags failed because the value is not there:

https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-title/index.js#L12

In fact, if you use Microlink API, the title value is there:

https://api.microlink.io/?url=https://snowflakegelato.co.uk

**Comment by alexpluto** [comment]
Thanks @Kikobeats, I'll have a look at using the API.

Out of interest, why wouldn't the library pick up on this value, but the API would?

And in general, would you recommend developers use the API instead of the library for better reliability?

**Comment by Kikobeats** [comment]
The thing is, metascraper is focused on extracting and normalizing data from HTML markup.

The hard (and painful) part there is getting the HTML content. 

so [microlink.io](https://microlink.io) is the hosted version of metascraper that also resolves the getting HTML content and provide the markup to metascraper for getting the data 🙂

**Comment by alexpluto** [comment]
Sounds like I need to have a look at the API ☺️
