### ISSUE TITLE
[Parsing Redirects] - Bloomberg site to Robot Page

### ISSUE THREAD

**Issue by byteshiva** [microlinkhq/metascraper#417]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Parsing redirects bloomberg site to robot page. How do we avoid this usecase 

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Code available at"
https://gist.github.com/byteshiva/c01a728d23f978deabb6a1729547ebb6

### Expected behaviour

Should return author and other details.
### Actual behaviour

Redirects to Bloomberg robot page
https://runkit.com/byteshiva/60b45e1749a6ad001b0cd0c6#

**Comment by Kikobeats** [comment]
sorry but that is a network issue rather than a metascraper thing

**Comment by Kikobeats** [comment]
Hey, 

I wrote a blogpost explaining what's happening there:

https://microlink.io/blog/proxy-capabilities/
