### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by formatically** [microlinkhq/metascraper#43]
This is more of a question than an issue. 

In the author's plugin, 
`wrap($ => $('meta[property="article:author"]').attr('content')),`
is listed second in the module export.  Does this mean that it has a higher priority than the other methods of extracting an author? 

Because I have noticed that if "article: author" is equal to a website url, then it is not used and a method further down the list is being used to extract the author.  

How is this working?  I do not see any code that is checking to see if its an URL or an actual authors name.

**Comment by Kikobeats** [comment]
You are right, rules have priority.

When a value needs to be resolved, rules are applied, from top to the bottom, so the position of the rule is important: The first rule that will resolve the value successfully, stop the pipeline of rules.

Rules work as fallback between them: If the first rule fails, then it fallback in the second rule; if the second rule fails, time to third fails,... until finish all the rule or find the first rule that resolves the value.

This is why when we are putting specific rules over generic rules are totally deliberate:

```js
module.exports = () => ({
  description: [
    // this rule is very specific, so the accurate of the rule is very nice!
    wrap($ => $('meta[property="og:description"]').attr('content')),
    // this rule is very generic, so we try to resolve it as last option, only when first rule fails
    wrap($ =>
      $('[class*="content"] > p')
        .first()
        .text()
    )
  ]
```

Another thing to keep in mind now with [plugins](https://github.com/microlinkhq/metascraper#plugins) is that the order of plugins is important.

Plugins add more rule per one or more properties, and these rules are added in order of appearance.

For example, if you declare a configuration file that uses plugins for extending `logo` property, you need to maintain the priority in the plugins declaration as well:

```yaml
#  .metascraperrc
rules:
  - metascraper-logo
  # `metascraper-logo-favicon` rules will be executed just when `metascraper-logo` doesn't resolve
  - metascraper-logo-favicon
```

**Comment by Kikobeats** [comment]
I'm going to close the issue but feel free to ask; Probably I should convert the reply into documentation 😄
