### ISSUE TITLE
Uncaught ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by wirtzdan** [microlinkhq/metascraper#434]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

I'm using metascraper in a Chrome extension. Recently the extension stopped working for a lot of users due to Chrome updating to version 92 and now requiring [cross-origin isololation](https://stackoverflow.com/questions/66489286/sharedarraybuffer-will-require-cross-origin-isolation-as-of-m91-around-may-2021).

### Expected behaviour

Normally, the extension should load just fine.

### Actual behaviour

But with the recent Chrome update, I get the error: `Uncaught ReferenceError: SharedArrayBuffer is not defined`. A little bit of digging shows me that it's caused in jsdom, which is loaded by metascraper/helpers. 

### How to reproduce

It should be reproducible by loading any kind of temporary chrome extension that initialises metascraper and uses packages like the metascraper-author package. 

---

Is this something that could be solved from your end? It's a [known problem](https://github.com/jsdom/webidl-conversions/issues/37) with jsdom, but it doesn't seem to be that case that they will fix it soon.

**Comment by Kikobeats** [comment]
Thanks for reporting but I feel there is not too much I can do there.

The error is clear: `SharedArrayBuffer` should be defined in the environment you are running metascraper, and as you said, that's actually a thing that happened after a Chrome update (the environment where you are running metascraper)

Maybe could be an approach to be sure `SharedArrayBuffer` exists, or load a shim instead?

Also as an alternative, you can consume (api.microlink.io)[https://api.microlink.io]. It runs metascraper under the hood, and the free API endpoint should be enough for little things (it has IP address rate limit)

**Comment by wirtzdan** [comment]
Thanks for the quick response. I also thought this could be the case. But I still appreciate the help. 

What do you mean by shim? 

Regarding the API limit: When it's limited per IP, that means I technically would get 100 request for free per user per day? Did I get that right?

**Comment by Kikobeats** [comment]
by `shim` means you can provide a `SharedArrayBuffer` as a global object for those scenarios where the object is undefined.

So you can monkey patch a global in order to resolve the issue. Something like this https://github.com/facebook/create-react-app/issues/10474#issuecomment-811987438

> Regarding the API limit: When it's limited per IP, that means I technically would get 100 request for free per user per day? Did I get that right?

That's right. The current free API rate limit is just 50 req/s per day, but I will be happy to increment to 100 if that resolves your issue. In case the user needs more, the user can [buy](https://microlink.io/#pricing) a plan and fill the API key to be attached as a header to the requests performed by the extension.
