### ISSUE TITLE
use TextDecoder for meta Content-Type

### ISSUE THREAD

**Issue by neyasov** [microlinkhq/metascraper#44]
Can you support it, global or from plugins?
```<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />```

**Comment by Kikobeats** [comment]
Hello,

The `HTML` that you must provide to metascraper must be interpreted correctly. so the task of providing the `HTML` with the correct character set is a precondition before passing it to metascraper.

The only thing metascraper does about `HTML` is a small normalization related to uppercase / lowercase:
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper/src/load-html.js#L7

Also, see how this is what we do in:
https://api.microlink.io/?url=https://pikabu.ru
