### ISSUE TITLE
Add metascraper-lang

### ISSUE THREAD

**Issue by palmiak** [microlinkhq/metascraper#45]
Hi

I would be interested in language property. These are the places I know where the language can be stored:
- html lang
- og:locale
- hreflang (https://moz.com/learn/seo/hreflang-tag) - but this part is needs most work and from what I see there could be errors here (many people only use href lang for other languanges than currently selected)

Thanks in advance.

**Comment by Kikobeats** [comment]
awesome idea! Probably soon, need to investigate a bit to determinate if we can add more rules around that 😄
