### ISSUE TITLE
Can I use 'import' instead of 'require'?

### ISSUE THREAD

**Issue by sebpowell** [microlinkhq/metascraper#453]
### Prerequisites

- [x ] I'm using the last version.
- [ x] My node version is the same as declared as `package.json`.

### Subject of the issue

I'm trying to convert the 'require' syntax shown in the documentation to 'import', but not having any luck. Here's my code:

```
import createMetaScraper from 'metascraper';
import metascraperAuthor from 'metascraper-author';

const metascraper = createMetaScraper([metascraperAuthor()]);
```

This gives me the following error:

`TypeError: (0 , metascraper_author_1.default) is not a function`

Not sure where I'm going wrong? Any guidance would be greatly appreciated.

**Comment by Kikobeats** [comment]
The library is using CJS, it's not ready for ESM.

I think it must be possible if you load https://github.com/standard-things/esm first.

**Comment by sebpowell** [comment]
@Kikobeats great, thanks!
