### ISSUE TITLE
Handling unescaped quotes in og:description

### ISSUE THREAD

**Issue by teddybradford** [microlinkhq/metascraper#455]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

I ran into a site with a malformed `og:description` that looks like this:

```html
<meta property="og:description" content=""It was like a shade had been pulled and then lifted."">
```

The quotes are unescaped. Is there a way to handle such cases?

### Expected behavior

Fix the malformed HTML and return a description.

### Actual behavior

No description is returned.

**Comment by Kikobeats** [comment]
It's actually a `cheerio` thing

```
> require('cheerio').load('<meta property="og:description" content=""It was like a shade had been pulled and then lifted."">')('meta').attr('content')
''
```

unfortunately that markup looks very malformed and can't be handled
