### ISSUE TITLE
Support for React / React Native clients 

### ISSUE THREAD

**Issue by AnhsirkDasarp** [microlinkhq/metascraper#485]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Request to remove hard dependency on node apis , to use it along with React native projects. 

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
It's not going to happen in the short/mid term, sorry!
