### ISSUE TITLE
Stopped by: require() of ES modules is not supported

### ISSUE THREAD

**Issue by JLKM** [microlinkhq/metascraper#496]
Awesome attempt to break the python dominance in this field. Thanks for that. Still, I simply can't make Metascraper run, like it should.

### 1. Two test-setups

1) Test on Windows 10 Home
Node version: 14.15.0
NPM version: 6.14.8

2) Test on Ubuntu 20.04 LTS
Node version: 16.13.1
NPM version: 8.1.2

### 2. Same procedure

Have followed the instructions from this tutorial:
Basic Metascraper for lists of urls - Hubert - Medium:
https://medium.com/@hubret/basic-metascraper-for-lists-of-urls-aa8f8636f344

Ending with attempt to run `npm run start`.

...with a few twists

1) index.js file copy-pasted (with URL replacement) from https://metascraper.js.org/#/

2) seperate installation of every rule/package mentioned in index.js (f.ex. `npm i -s metascraper-author`)

### 3. Almost the same error occurs in Windows and Ubuntu

WINDOWS:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: F:\metascraper2\node_modules\got\dist\source\index.js require() of ES modules is not supported.

require() of F:\metascraper2\node_modules\got\dist\source\index.js from F:\metascraper2\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.

Instead rename F:\metascraper2\node_modules\got\dist\source\index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from F:\metascraper2\node_modules\got\package.json. 

```

UBUNTU:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/jan-larsen/metascraper1/node_modules/got/dist/source/index.js from /home/jan-larsen/metascraper1/index.js not supported.

Instead change the require of /home/jan-larsen/metascraper1/node_modules/got/dist/source/index.js in /home/jan-larsen/metascraper1/index.js to a dynamic import() which is available in all CommonJS modules.
```

### 4. Attempts to fix
I have fiddled around with:
- File-extensions - .js => .cjs
- Inserting `"type": "module"` in parent package.jsons

...but no luck.

### 5. Questions
1) Is it an issue with the `got`-library (which often turns up in the error-logs)?
2) What would be the easiest way to get this up and running without the mentioned error messages?

**Comment by Kikobeats** [comment]
Hello, I think this is going to work if you install got@11

instead of `npm i -s got`, try performing `npm i -s got@11`

**Comment by JLKM** [comment]
Thx a lot. Works like a charm. At least on my Ubuntu-setup. Haven't tested it on Windows.
