### ISSUE TITLE
How to integrate custom ruleset?

### ISSUE THREAD

**Issue by agchou** [microlinkhq/metascraper#51]
Are there any examples of a custom rule set in a project? The documentation, to me, isn't clear enough. Where do I save the custom ruleset? How do I require it in the rc file?

I'm running docker + node.

**Comment by agchou** [comment]
I ended up just publishing my own custom ruleset on NPM and am using that in my project.

**Comment by Kikobeats** [comment]
Sounds good! Can you share with us the module?

Also, help for improving documentation is welcome 🙂

**Comment by agchou** [comment]
It's just a modified version of the metascraper-amazon one, I'll probably switch back to the official after / if I do a pull request :P

Is there an easier way to do a custom ruleset without publishing my own package on NPM? I would help with documentation if I knew how to do it haha!

**Comment by Kikobeats** [comment]
Definitely I need to add a section about how to setup the project locally for reduce the friction in issues like that 😄 

1. Fork the repository and clone it:  `git clone git@github.com:microlinkhq/metascraper.git`.
2. Run npm install. It automatically link all packages together on the [post installation script](https://github.com/microlinkhq/metascraper/blob/master/package.json#L40).

In case to improving a specific metascraper module, for example, `metascraper-amazon`:

1. Setup a new unit test. For do that you need two things a preconditions: 
 1.1. The target url, for example: `https://www.amazon.es/aspirador-Excellence-Programable-limpieza-Silencioso/dp/B01MUGXRT9`
 1.2 The HTML behind the url as a static fixture ([example](https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-amazon/test/fixtures/amazon-co-uk)). You can copy/paste from the browser or download using a CLI command, like: `curl https://www.amazon.es/aspirador-Excellence-Programable-limpieza-Silencioso/dp/B01MUGXRT9 > fixture.html`

2. Declare the uni test. [Example](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-amazon/test/index.js#L58)
3. In the test assertion, we use (snapshots)[https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-amazon/test/index.js#L66]. They live at [\_\_snapshots__](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-amazon/__snapshots__/index.js.snap-shot#L34) folder.
4. Adjust the snapshot for the expected output, and then change the code for make possible [this happens](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-amazon/index.js#L51)!

I hope this clarify you how to contribute, feel free to feedback me

**Comment by thomasobrien99** [comment]
I am also running into this today. I am trying to define a custom rule in a .js file in the root of my project (same directory as .metascrapperrc) but in load-rules.js 
```
const modulePath = resolveFrom(cwd, moduleName)
return require(modulePath)(moduleConfig)
```
 `resolveFrom` is throwing an error (basically saying it can't find the file). Although the cwd appears to be correct. Any ideas what I am doing wrong?

**Comment by agchou** [comment]
@thomasobrien99 can you share your code for your .metascraperrc?

**Comment by thomasobrien99** [comment]
@agchou sure! 
```
{
  "rules": [
    "metascraper-author",
    "metascraper-date",
    "metascraper-description",
    "metascraper-image",
    "metascraper-lang",
    "metascraper-logo",
    "metascraper-logo-favicon",
    "metascraper-logo",
    "metascraper-publisher",
    "metascraper-title",
    "metascraper-url",
    "./metascraper-rules"
  ]
}
```
although I think a lot of those are default, so I will remove them. But there is a file in the root directory (same as .metascraperrc), called `metascraper-rules.js` that exports another rule.

**Comment by Kikobeats** [comment]
@thomasobrien99 your comment is so valuable!

Probably the documentation is vague because I'm a little pollute about the user case context at the first time.

Can you make a PR adding that? I would be very grateful 😄

**Comment by thomasobrien99** [comment]
@Kikobeats sure, will do!

**Comment by Kikobeats** [comment]
any status? 😄
