### ISSUE TITLE
Doesn't recognize a metascraperrc/package.json OR looks for them in a different path when running from node_modules?

### ISSUE THREAD

**Issue by coolreader18** [microlinkhq/metascraper#52]
I have a package published that uses metascraper, yet it doesn't seem to draw from either a metascraperrc or the metascraper section of package.json, when it's in node_modules. It works when testing in its own directory, but not as a package. Am I doing something wrong, or is this a scoping issue? It could also be that I'm using a local rule, such as `./rule.js`, which it might be looking for in the root directory of the project that has it as its dependency.

**Comment by Kikobeats** [comment]
Could be easy to reproduce setup a `package.json` with `metascraper` property here instead of use the `rc` file:

https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper/test/unit/custom-rules

**Comment by Kikobeats** [comment]
I added [METASCRAPER_CWD](https://github.com/microlinkhq/metascraper#metascraper_cwd) documentation for do that 👍
