### ISSUE TITLE
Is it possiable to extract without inputting url as a parameter?

### ISSUE THREAD

**Issue by immortal-autumn** [microlinkhq/metascraper#522]
I am using the latest version of metascraper, I would ask whether it is possible to extract with local file location without inputting URL as an input parameter?

For example:

;(async () => {
  const { body: html, url } = await got(targetUrl)
  const metadata = await metascraper(html)
  console.log(metadata)
})()

**Comment by Kikobeats** [comment]
Hello,

The `url` is required mostly for resolving relative URLs detected over the HTML markup into absolute.

Knowing that, you can just provide a mock URL, like `'http://localhost'` 🙂

**Comment by immortal-autumn** [comment]
It returns an error message like this:

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error [MetascraperError]: INVALID_URL, Need to provide a valid URL.
    at new Error (E:/metascraper-5.28.6/metascraper-5.28.6/bench/node_modules/whoops/lib/create-extend-error.js:11:19)
    at E:/metascraper-5.28.6/metascraper-5.28.6/bench/node_modules/metascraper/src/index.js:22:13
    at E:/metascraper-5.28.6/metascraper-5.28.6/bench/test.js:13:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'INVALID_URL',
  description: 'Need to provide a valid URL.'
}

Why do this happens?

**Comment by immortal-autumn** [comment]
The code is as follows:

const mock = String('http://localhost')

;(async () => {
  const { body: html, url } = await got(targetUrl)
  const metadata = await metascraper({ html,  mock})
  console.log(html)
  console.log(typeof url)
  console.log(metadata)
})()

**Comment by immortal-autumn** [comment]
It will print an error:
Await is only valid in async functions and the top-level bodies of modules
