### ISSUE TITLE
How to debug Metascaper

### ISSUE THREAD

**Issue by kennethstarkrl** [microlinkhq/metascraper#523]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Some links hang and never return a response.

Is there a way to debug metascaper or give a verbose output? I'm having issues with some links hanging and metascaper doesn't return a response.  Some links do work and some do not. On my localhost the non-working links do work so I believe its a networking issue in my production environment somewhere and I'm trying to figure out where the hang-up is. 

Thank you.

**Comment by Kikobeats** [comment]
Hello,

I'm confused because metascraper doesn't perform a network request for getting the HTML; instead, you should to provide it as argument:

```
const metascraper = require(https://github.com/microlinkhq/metascraper)([
  require(['metascraper-author'](https://nicedoc.io/microlinkhq/metascraper/packages/metascraper-author))(),
  require(https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-date)(),
  require(https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-description)(),
  require(https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-image)(),
  require(https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-logo)(),
  require(https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-clearbit)(),
  require(https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-publisher)(),
  require(['metascraper-title'](https://nicedoc.io/microlinkhq/metascraper/packages/metascraper-title))(),
  require(['metascraper-url'](https://nicedoc.io/microlinkhq/metascraper/packages/metascraper-url))()
])

const got = require(https://github.com/sindresorhus/got)

const targetUrl = 'http://www.bloomberg.com/news/articles/2016-05-24/as-zenefits-stumbles-gusto-goes-head-on-by-selling-insurance'

;(async () => {
  const { body: html, url } = await got(targetUrl)
  const metadata = await metascraper({ html, url })
  console.log(metadata)
})()
```

In any case, for debugging, just set `DEBUG=metascraper*` to see all the internal details.

or just pass the URL to Microlink API that is hosting metascraper under the hood.

.e.g,: [api.microlink.io?url=https://teslahunt.io](https://api.microlink.io?url=https://teslahunt.io)
