### ISSUE TITLE
Demo code on homepage is not working because of got.

### ISSUE THREAD

**Issue by fabio-C** [microlinkhq/metascraper#543]
### Prerequisites

- [ x] I'm using the last version (^5.29.6)
- node version: v16.15.0

### Subject of the issue

The demo code in this page (https://metascraper.js.org/#/) is not working because of this:
https://bobbyhadz.com/blog/javascript-got-error-err-require-esm-of-es-module

```
const got = require('got')
            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/fabio/Documents/Projects/Bookmarks/scraperTest/node_modules/got/dist/source/index.js from /home/fabio/Documents/Projects/Bookmarks/scraperTest/index.js not supported.
Instead change the require of /home/fabio/Documents/Projects/Bookmarks/scraperTest/node_modules/got/dist/source/index.js in /home/fabio/Documents/Projects/Bookmarks/scraperTest/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/fabio/Documents/Projects/Bookmarks/scraperTest/index.js:11:13) {
  code: 'ERR_REQUIRE_ESM'
}

```
The got library doesn't support **require** anymore.

The solution is to install an older version: `npm install got@11.8.3`

You should change the example.

**Comment by Kikobeats** [comment]
Thanks for notifying; I updated the example to use [undici](https://undici.nodejs.org) instead 🙂
