### ISSUE TITLE
Cannot read property 'DOCUMENT_MODE' of undefined

### ISSUE THREAD

**Issue by 6696ram** [microlinkhq/metascraper#551]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is 12 or 14.

 This issue is from version > 5.16.0 where the import in load-html file is being changed from `require('cheerio-advanced-selectors').wrap(require('cheerio'))
` to `require('cheerio')`

### Cannot read property 'DOCUMENT_MODE' of undefined

I am getting the link using `got or fetch` when passed to the metascraper Object to get the data, it is giving the above mentioned error

```
const {
            body: html,
            url
        } = await got(targetUrl)
        const metadata = await metascraper({
            html,
            url
        })
        console.log(metadata) 
```
#

**Comment by Kikobeats** [comment]
Sorry, but I can't reproduce the issue with this information.

You should to follow the issue template and create a reproducible example using
https://npm.runkit.com/metascraper

**Comment by 6696ram** [comment]
@Kikobeats 
I was using node version 12
This was because of the `parse5` package which metascraper internally uses, Installing the parse5 package explicitly worked for me
