### ISSUE TITLE
HOW TO DOWNGRADE LATEST VERSION!?!

### ISSUE THREAD

**Issue by xlmnxp** [microlinkhq/metascraper#556]
Thank you,
today metascraper updated and it has package named `@metascraper/helper` that use it own version of jsdom which is `20.0.0` and it not compatible with my node version in staging and production!

I tried many ways without fix:
use override in package.json
```
    "overrides": {
        "@metascraper/helpers": {
            "jsdom": "19.0.0"
        }
    },
```

change version of metascraper to fixed version:
```
        "metascraper": "5.25.6",
        "metascraper-description": "5.25.6",
        "metascraper-image": "5.25.6",
        "metascraper-title": "5.25.6",
```

even using resolutions:
```
    "scripts": {
        "preinstall": "npm-force-resolutions",
        "start": "nodemon -L -r dotenv/config --ignore './upload/' --ignore './uploads-docs/' ./server.js"
    },
    "resolutions": {
        "jsdom": "19.0.0",
        "@metascraper/helpers": "5.25.6"
    }
```

that update break our application

**Comment by xlmnxp** [comment]
look like add the following to dependencies fix the issue
```
"@metascraper/helpers": "5.25.6"
```

**Comment by Kikobeats** [comment]
Hello,

which node version are you using?
