### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by onsombal** [microlinkhq/metascraper#57]
I believe this is an issue of how metascraper use of "**require()**" works with **webpack** design. I wish to ask if you can offer any direction to fix these errors I'm getting when using metascraper with vue.js, which uses webpack. Below is something I learned about webpack by referencing an example of how webpack expects **require()** to work:

    var module_path= "./dir/"+somevariable+".js";
    var foo= require(module_path);

• **require("./dir/"+somevaribale+".js")** is statically analyzable, so it works with webpack
• **require(module_path)** is not statically analyzable, so it doesn't work with webpack.
Webpack calls this feature "**require context**" and its behavior is by design.

**Referencing one of the warnings** -- warning  in **./node_modules/metascraper/src/load-rules.js**
- 52:15-34 Critical dependency: the request of a dependency is an expression
- the offending code in **load-rules.js** seems to be with all the "**require()**" statements that are referencing variables.

**QUESTION**:  Is there a way to resolve this issue so metascraper can be used with webpack?

Thanks... Jim
__________________________________

### Prerequisites

- [ Yes ] I'm using the last version of metascraper.
- [ 5.6.0 ] My npm version is the same as declared as `package.json`.
- [ v6.11.1 ] My node version is the same as declared as `package.json`.
- "vue": "^2.5.2",
-  "webpack": "^3.6.0",
-  "webpack-bundle-analyzer": "^2.9.0",
-  "webpack-dev-server": "^2.9.1",
-  "webpack-merge": "^4.1.0"

### Critical dependency: the request of a dependency is an expression

PLEASE SEE THE SEVEN WARNINGS BELOW. 
```
# npm run dev

 WARNING  Compiled with 7 warnings                                 

 warning  in ./node_modules/keyv/src/index.js

18:14-40 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/metascraper/src/load-rules.js

52:15-34 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/lazy-debug-legacy/src/functions.js

62:15-40 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/lazy-debug-legacy/src/functions.js

87:8-28 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/css/node_modules/source-map/lib/source-map/source-map-generator.js

8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/css/node_modules/source-map/lib/source-map/source-map-consumer.js

8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/css/node_modules/source-map/lib/source-map/source-node.js

8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

```

**Comment by onsombal** [comment]
After more research, it appears there are some major issues relating to changes required when migrating from webpack-1 to webpack-2 -- ref: https://webpack.js.org/guides/migrating/#full-dynamic-requires-now-fail-by-default

**QUESTION**:  Are there plans to migrate metascraper to support webpack-2 ?

Thanks... Jim

**Comment by Kikobeats** [comment]
I suppose you are using webpack to generate a browser bundle.

Currently, the project is not ready for supporting browser side.

Internally metascraper needs `require` for load bundles rules:
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper/src/load-rules.js#L52

If you have a better approach to resolving that, PR is welcome 💃
