### ISSUE TITLE
`metascraper@5.29.17` adds required `validateUrl` property to `ScrapOptions` (breaking change in patch release)

### ISSUE THREAD

**Issue by KeithGillette** [microlinkhq/metascraper#570]
### Prerequisites

- [X] I'm using the last version.
- [X] My node version is the same as declared as `package.json`.

### Subject of the issue

MetaScraper 5.29.17 adds a new required boolean property `validateUrl` to the `ScrapOptions` interface but [the documentation](https://github.com/microlinkhq/metascraper/blob/master/README.md#validateurl) indicates that this new property has a default value of `true`, implying that it should be optional. The new required property added in this patch release breaks calling code.

### Steps to reproduce

Pass arguments to the Scraper.

### Expected behaviour

The `validateUrl` property of `ScrapOptions` should be optional.

### Actual behaviour

The `validateUrl` property of `ScrapOptions` is required.

**Comment by KeithGillette** [comment]
Thanks for the fast attention to this, @Kikobeats. It certainly looks like the change should correct the issue. How do I construct the NPM URL to install that commit on the `metascraper` package to install and test?

**Comment by Kikobeats** [comment]
Shipped `metascraper@5.29.18`; can you try it? 🙂

**Comment by KeithGillette** [comment]
All good now. Thanks!
