### ISSUE TITLE
Metascraper returns only {}

### ISSUE THREAD

**Issue by PixelPage-YT** [microlinkhq/metascraper#585]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

I'm using metascraper with es6 imports and node fetch, but it only returns an empty object ({}).

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

```
import metascraperImage from "metascraper-image";
import metascraperTitle from "metascraper-title";
import metascraperUrl from "metascraper-url";
import metascraperShopping from "@samirrayani/metascraper-shopping"
import fetch from 'node-fetch';
import metascraper from "metascraper"

const ms = metascraper([
    metascraperImage,
    metascraperShopping,
    metascraperTitle,
    metascraperUrl
])

const fetched = await fetch(link);
const html = await fetched.text();
const data = await ms({url:link,html:html})

console.log(data) // Returns "{}"
```

### Expected behaviour

The object should contain the metadata of the url

### Actual behaviour

I only get {}

**Comment by Kikobeats** [comment]
Please, reproduce the problem at https://npm.runkit.com/metascraper 🙂

**Comment by PixelPage-YT** [comment]
@Kikobeats runkit does not support 'import'

**Comment by Kikobeats** [comment]
then can you make a github repo to reproduce the issue?

Note this library is CommonJS, so probably that's the thing.

**Comment by jarne** [comment]
I was experiencing the same problem, and was able to fix it, it was only a really minor thing:

This was giving the empty result like described in the issue:

```js
import metascraper from "metascraper"
import mTitle from "metascraper-title"
import mDescr from "metascraper-description"
import mLogo from "metascraper-logo"
import mImage from "metascraper-image"

const ms = metascraper([mTitle, mDescr, mLogo, mImage])
```

Replacing the last line with this, however, fixed the issue (notice the brackets after the imported rule modules):

```js
const ms = metascraper([mTitle(), mDescr(), mLogo(), mImage()])
```

That's actually also how it's done in the [readme](https://github.com/microlinkhq/metascraper?tab=readme-ov-file#importing-rules), I likely just missed it when converting the imports to ES6.
