### ISSUE TITLE
pointers for writing rules for multiple meta dc.subject tags?

### ISSUE THREAD

**Issue by emckean** [microlinkhq/metascraper#598]
### Prerequisites

- [X ] I'm using the last version.
- [X ] My node version is the same as declared as `package.json`.

### Subject of the issue

I'm looking to write a package that would create an array of 'dc.subject' tags. There are usually multiple dc.subject tags in the html, like so: 

````
<meta name="dc.subject" content="Astronomy and astrophysics"/>

<meta name="dc.subject" content="Careers"/>

<meta name="dc.subject" content="Research management"/>
````

If only the first tag matches for rules, can anyone give me pointers for handling multiple tags of the same name?

I poked around in some of the other packages but they mostly seem to be "one tag, one match" rules.

**Comment by Kikobeats** [comment]
can you try `$('dc.subject').first()` ?

**Comment by emckean** [comment]
Thank you! I'll poke at that a bit. :) 

Ideally, I'd like an array of all dc.subject values, so ['Astronomy and astrophysics','Careers','Research management']

**Comment by Kikobeats** [comment]
Then check `$filter` implementation, I think it will help you to understand how to manipulate a collection of selectors.

I'm going to close this, but feel free to continue the conversation 🙂
