### ISSUE TITLE
Target Node 8.x

### ISSUE THREAD

**Issue by gabrielalmeida** [microlinkhq/metascraper#60]
Node 8 is great and everybody should update ASAP, but unfortunately, it's not always that easy.

Node [6.x is still Active LTS status](https://github.com/nodejs/Release) and [some](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) [great](https://cloud.google.com/functions/docs/writing/) [services](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version-and-package-management) don't support 8.x yet.

Also, adoption isn't widespread yet:

![image](https://user-images.githubusercontent.com/310382/35779298-e65eacc8-09b1-11e8-8c51-c1846f1f8210.png)

> In this, you can see the three release lines represented by solid green (Node.js 4 "Argon"), solid blue (Node.js 6 “Boron”), and solid purple (Node.js 8 “Carbon”).
>
> Throughout the year, you can see Node.js 6 reigning supreme—peaking at 388,417 downloads on October 25th. Unlike last year with Node.js 6 and Node.js 4, the downloads of Node.js 8 didn’t surpass the downloads of the Node.js 6 LTS. This is an interesting trend that we should watch into the new year. It seems that the majority of downloads of Node.js are still Node.js 6, even though Node.js 8 has been trending upward for the past few months.
>
> Given the data, it may be safe to assume that the delayed LTS-adoption trend will continue, and as Node.js usage continues to grow, adoption of new LTS versions could very well take longer and longer with each new LTS cycle. We’ll be able to confirm or reassess this assumption with next year’s data, though!

Source: [NodeSource](https://nodesource.com/blog/digging-into-node-by-numbers-2017)

I found that the library [aimed](https://github.com/microlinkhq/metascraper/issues/15) to [support](https://github.com/microlinkhq/metascraper/issues/18) [Node 4.x](https://github.com/microlinkhq/metascraper/issues/19) and [browser](https://github.com/microlinkhq/metascraper/tree/78ec62beb8d82ded033d92653ad8dec022b8573d#browser-side-usage) back in the old days by [transpiling via Babel](https://github.com/microlinkhq/metascraper/blob/78ec62beb8d82ded033d92653ad8dec022b8573d/package.json#L11) but I couldn't find a notice about dropping support to these environments on Changelog/Release Notes (Although there is a [`Remove browser mention` commit](https://github.com/microlinkhq/metascraper/commit/6cb0d73)).

Cloud Function providers are probably going to support 8.x soon as this is [The Right Thing™](https://www.ibm.com/blogs/bluemix/2017/12/new-node-js-8-runtime-ibm-cloud-functions/) but they're [moving](https://forums.aws.amazon.com/thread.jspa?threadID=264534) [slowly](https://cloud.google.com/functions/docs/release-notes).

So, would maintainers consider accepting a PR adding back Babel to enable this great library at least on 6.x runtime in the meantime or while marked as LTS?

Thanks for working on OSS projects!

**Comment by Kikobeats** [comment]
[Currently node 8 is the main target](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper/package.json#L84)
