### ISSUE TITLE
Add video support for YouTube

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/metascraper#62]
The new `video` property need to be an absolute video url.

Looks like we can use a service for composing the final url, like
https://weibomiaopai.com/online-video-downloader/youtube

Investigate about that!

**Comment by breadadams** [comment]
It's in php, but could be of use to you @Kikobeats https://github.com/LookHin/MP4-FROM-YOUTUBE

**Comment by Kikobeats** [comment]
Better don't use hacky stuff, better get the video using the iframe support
