### ISSUE TITLE
Return multiple images?

### ISSUE THREAD

**Issue by jamesrgrace** [microlinkhq/metascraper#626]
### Subject of the issue

Love this library, thanks!  I'm looking for the ability to return multiple matches, specifically for images, although I think it might be useful for other rules as well.  

### Steps to reproduce

Extract meta for any URL.

### Expected behaviour

I'd love to be able to get 
{
 image: ["img1","img2"]
}

or
{
 image: [{url: "foo", size: 1000}, {url: "bar", size: 2000}]
}

### Actual behaviour

Only the first image match is returned.

**Comment by Kikobeats** [comment]
Hello, maybe that could the [opportunity](https://github.com/microlinkhq/metascraper/blob/master/CONTRIBUTING.md) for creating a new package for that case 🙂

The `metascraper-image` is returning one image because rules like `og:image` are oriented to specify just one image.
