### ISSUE TITLE
How to get twitter:card

### ISSUE THREAD

**Issue by nekochan0122** [microlinkhq/metascraper#628]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

![image](https://user-images.githubusercontent.com/47508893/227187554-6c4bc67e-7b18-486e-9650-96f43f345dd2.png)

**Comment by Kikobeats** [comment]
Hello,

The issue template is there for a reason. With no words, it is quite hard to understand what you want.
