### ISSUE TITLE
Add video support for Twitter

### ISSUE THREAD

**Issue by breadadams** [microlinkhq/metascraper#63]
It seems Twitter [_released_](https://twittercommunity.com/t/twitter-video-support-in-rest-and-streaming-api/) the ability to get raw videos via their API.

We need to use this so the `video` property will be an absolute path (as with #62).

**Comment by Kikobeats** [comment]
cool!

The problem with this approach is that currently all your rules are based on the HTML markup. It's fast to read and extract content.

Delivering the data extraction to an API have other implications related to API quota and this kind of information that we can't keep under control without unexpected errors.

Need to investigate.

**Comment by Kikobeats** [comment]
Example of URL for Twitter:
https://twitter.com/UFC_AUSNZ/status/961082966838398977

**Comment by Kikobeats** [comment]
For the moment avoid depends of third party API's
