### ISSUE TITLE
[metascraper-lang] Wrong language detection

### ISSUE THREAD

**Issue by palmiak** [microlinkhq/metascraper#64]
Hi

I'm developing a site that is using microlink to gather data from pages. It works amazing - I just found a problem with language detection on one site:

http://www.dwutygodnik.com/artykul/7615-churchill-bohater-naszych-czasow.html

lang: en - which is wrong it should be 'pl'.

I checked the source of the website and it looks ok:
`<html lang="pl" >`

**Comment by Kikobeats** [comment]
Hey!

Hmm strange, I need to write a test for that but the rule related with lang matching looks clear:
https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-lang/index.js#L13

🤔

**Comment by Kikobeats** [comment]
Release at `v3.7.3`, thanks!
