### ISSUE TITLE
Not scrapping the correct date

### ISSUE THREAD

**Issue by ghmendonca** [microlinkhq/metascraper#649]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

The `metascraper-date` is returning the wrong dates for this page:

https://www.fda.gov/food/food-additives-petitions/aspartame-and-other-sweeteners-food

If you look the meta tags, both `og:updated_time` and `article:modified_time` has the value `Fri, 07/14/2023 - 10:30` but yet the metascraper is returning `2023-07-21T12:00:00.000Z`. It's interesting that this date can't be find anywhere in the HTML.

Also, the published date is also wrong, the meta tag `article:published_time` has the value `Tue, 07/11/2023 - 17:57` but the metascraper is returning `2023-07-18T12:00:00.000Z`.

### Expected behaviour

Return the correct dates, based on the meta tags.

### Actual behaviour

Returning wrong dates that are not even in the HTML.

**Comment by Kikobeats** [comment]
Hello, and thanks for reporting. A couple of questions:

- is `og:updated_time` a valid open graph tag? I can't see it at https://ogp.me.
- after add an e2e, the `date` comes from the [first](https://github.com/microlinkhq/metascraper/blob/9b252df7aaa9b553774c21f1152f19e67f92ac52/packages/metascraper-date/index.js#L22) rule.

```
❯ $jsonld('dateModified')
'Fri, 07/14/2023 - 10:30'
❯ date($jsonld('dateModified'))
'2023-07-21T10:00:00.000Z'
```
