### ISSUE TITLE
Crash on `metascraper-audio`

### ISSUE THREAD

**Issue by ulfgebhardt** [microlinkhq/metascraper#661]
### Prerequisites

- [x] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.
> Have not declared a node version in the package.json

![image](https://github.com/microlinkhq/metascraper/assets/1238238/b5057dd6-c5c2-43e8-8449-8da2ffa7d538)

### Subject of the issue

`metascraper-audio` crashes unrecoverable during runtime

### Steps to reproduce

![image](https://github.com/microlinkhq/metascraper/assets/1238238/8551b184-4dc3-4c8e-a3c1-6d01074ce244)

```
import Metascraper from 'metascraper'
import fetch from 'node-fetch'

const metascraper = Metascraper([
  require('metascraper-author')(),
  require('metascraper-date')(),
  require('metascraper-description')(),
  require('metascraper-image')(),
  require('metascraper-lang')(),
  require('metascraper-logo')(),
  require('metascraper-publisher')(),
  require('metascraper-title')(),
  require('metascraper-url')(),
  // require('metascraper-audio')(), << this line crashes
  require('metascraper-soundcloud')(),
  require('metascraper-video')(),
  require('metascraper-youtube')(),
])

const fetchResource = async (url) => {
  console.log('fetchResource', url)
  const response = await fetch(url)
  console.log('fetchResource1')
  const html = await response.text()
  console.log('fetchResource2')
  const resource = await metascraper({ html, url })
  console.log('fetchResource3')
  return {
    sources: ['resource'],
    ...resource,
  }
}

fetchResource('https://transinformation.net/offener-brief-an-den-widerstand-warum-lichtarbeiter-sich-gegenseitig-angreifen/')
```

When scraping the url `https://transinformation.net/offener-brief-an-den-widerstand-warum-lichtarbeiter-sich-gegenseitig-angreifen/` we get in our setup a crash shown in the screenshot when using `metascraper-audio`.

The crash seems to occur in foreign js-code within the jsdom library.

### Expected behaviour

`metascraper-audio` does not crash unrecoverable during runtime

### Actual behaviour

`metascraper-audio` crashes unrecoverable during runtime

**Comment by Kikobeats** [comment]
I experienced some similar cases like that; It seems the markup loaded by jsdom is creating side effects.

It isn't clear to me how to handle these errors; any idea?

**Comment by ulfgebhardt** [comment]
`try ...catch` didn't do the trick for us - we don't know at the given time.

**Comment by Kikobeats** [comment]
maybe related:
https://github.com/jsdom/jsdom/issues/2346

as a workaround we can try to run the library in a worker threads

**Comment by Kikobeats** [comment]
I will close this for now since the ideal solution is to fix this behavior in jsdom.

Also, you can pass your own way to get the iframe
https://github.com/microlinkhq/metascraper/blob/233b4a62054409bcbf634a9421908bbe2cb77065/packages/metascraper-audio/index.js#L77C21-L77C30
