### ISSUE TITLE
metascraper-date typing errors

### ISSUE THREAD

**Issue by timothyallan** [microlinkhq/metascraper#682]
### Prerequisites

- [X ] I'm using the last version. (^5.42.5)

Something is up with the types, I was using things fine a few days ago, but now can't compile my typescript project anymore with 5.42.5 as I now get errors from the date types:

```
node_modules/metascraper-date/src/index.d.ts(14,24): error TS1015: Parameter cannot have question mark and initializer.
node_modules/metascraper-date/src/index.d.ts(14,24): error TS2371: A parameter initializer is only allowed in a function or constructor implementation.
```

**Comment by Kikobeats** [comment]
Thanks for reporting; It should be fixed in the latest version, can you verify? 🙂

**Comment by timothyallan** [comment]
All fixed, thanks @Kikobeats !
