### ISSUE TITLE
Any issues with a memory leak, particularly metascraperDescription()

### ISSUE THREAD

**Issue by DanDubinsky** [microlinkhq/metascraper#693]
### Prerequisites

- [ ] I'm using the last version. - Looks like are servers are using 5.34.9. I've tried with older and newer versions on my local dev environment and it seems like every version has the issue.
- [ X] My node version is the same as declared as `package.json`. - Servers and local are using node v 18

### Subject of the issue

We've been getting some out of memory errors on our servers that run metascraper. If we have some large HTML, over 3mb the memory usage can spike up to 300mb - 500mb. If there are several at once it can crash the server. We put a limit so that no html over 2.5 gb gets processed and that stopped the crashing, but now we seem to have a slow leak. The servers runs out of memory after about 3 days. The problem seems to occur with the metascraperDescription() rule mostly.

For example this seems to make the issue much worse

const mdUtil = createMetascraper([
  metascraperDescription(),
  metascraperImage(),
  metascraperTitle(),
  metascraperUrl(),
])

With this it doesn't use nearly as much memory

const mdUtil = createMetascraper([
  //metascraperDescription(),
  metascraperImage(),
  metascraperTitle(),
  metascraperUrl(),
])

**Comment by Kikobeats** [comment]
Unfortunately I have to close this. The code snippet provided is probably a tiny part of all your whole application.
