### ISSUE TITLE
[metascraper-image] ability to pick desired image

### ISSUE THREAD

**Issue by aldenquimby** [microlinkhq/metascraper#722]
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

On some sites, `metascraper-image` returns unwanted images. Ideally there'd be more fine grained control to pick a desired image.

### Steps to reproduce
Example HTML:
```html
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="format-detection" content="telephone=no">
  <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
  <title>ArcGIS Web Application</title>
  <link rel="shortcut icon" href="images/shortcut.ico">
</head>
<body class="claro jimu-main-font">
  <article>
    <img src="./close-icon.png">
  </article>
  <div>
    <img src="./hero.png">
  </div>
</body>
```

### Expected behaviour
- some way to choose `hero` over `close-icon`
- _or_ some way to have no image at all returned

### Actual behaviour
- `close-icon` is returned as the image. there is no way to pick `hero` instead

### Tech Proposal

Idea 1 - introduce a `pickFn` option to `metascraper-image`, similar to what already exists in `metascraper-logo-favicon`
- function would receive a list of all the images found and return the one to use
- or it could be an `isAllowed` filter function to operate on 1 image at a time if that's easier

Idea 2 - introduce `findInBody` flag to optionally only look at `meta` vs checking both `meta` and body
- this is how Slack URL expansion works
- this would solve my particular use case, as it'd be fine for me to have no image in this case

**Comment by Kikobeats** [comment]
Hello,

I'm not seeing how to land this. The purpose of `metascraper-image` is to get a social media image.

In case the website doesn't have any kind of metadata tag in the markup, the library try to do best effort, running the following rules: https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-image/src/index.js#L19-L26

Just in that case the result can be very arbitrary, but that is a corner case, not the expected generic behavior.

> some way to choose hero over close-icon

That is very specific for a specific HTML markup. If you want to pick hero, then just create metascraper rule and load them befhore loading `metascraper-image`

```js
const heroRules = () => {
  const rules = {
    image: [
      ({ htmlDom: $, url }) => $('img[src="hero.png"]').attr('src')
    ]
  }
  return rules
}


const metascraper = require('metascraper')([
  heroRules(),
  require('metascraper-image')(),
])
```
