### ISSUE TITLE
Youtube links return successful response in production but some fields null or incorrect 

### ISSUE THREAD

**Issue by lljr** [microlinkhq/metascraper#729]
### Prerequisites

- [ ] I'm using the last version. (5.45.22)
- [ x ] My node version is the same as declared as `package.json`.

### Subject of the issue

Youtube links come back with `null` author and title fields but the request is successful. I've added `metascraper-youtube` package but Youtube links are not scraped correctly, meaning that I'm not even getting the Youtube link's title, only `- Youtube`. 

The fetch is done via native `fetch` method. This does work locally but not in production. I read https://github.com/microlinkhq/metascraper/issues/413, which seems to be the same issue I'm running into... I thought the setup is straightforward but maybe I'm missing something? 
### Steps to reproduce

more or less the same as in https://github.com/microlinkhq/metascraper/issues/413#issuecomment-849493819

Tell us how to reproduce this issue.

### Expected behaviour

Youtube link with correct title and description. 

### Actual behaviour

 ```
{ author: null, description: null, title: "- Youtube" }
```

**Comment by Kikobeats** [comment]
What means "production" here?

**Comment by Kikobeats** [comment]
Hello, that's happening because the HTML returned by your network response doesn't contain what is the library expecting.

So the issue is not related with the library; it's related to how to get the HTML!

**Comment by bhurlow** [comment]
in case anyone stumbles on this, we found that requests from fly.io to youtube were getting a bot/captcha page that was still being returned status 200. That page does not have any `og` metadata on it. We found using the youtube API was a fairly straightforward solution
