### ISSUE TITLE
metascraper node -v 6.11.5 compatible

### ISSUE THREAD

**Issue by daviswhitehead** [microlinkhq/metascraper#73]
Hi, is there a version of metascraper that's compatible with node 6.11.5? I'm trying to use metascraper within a firebase cloud functions project and that requires using node 6.11.5.

**Comment by Kikobeats** [comment]
Unfortunaly we don't maintain different node versions.

You can follow two approach:

- Ship a node >= 8 binary with your Google Function bundle.
- Transpile the code to node 6 target, for example, using [babel-preset-env](https://github.com/babel/babel-preset-env)
