### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [microlinkhq/metascraper#74]
Hi,

I'm a member of the Node.js Security WG and we received a report regarding a security issue with this module.

We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

**Comment by Kikobeats** [comment]
Hey,

I saw the mail but unfortunately no time to priorize this.

PR are welcome!

**Comment by Serkan-devel** [comment]
Isn't a security issue a priority? My PR has been untouched for months for example https://github.com/Minds/minds/pull/77 . How quickly do they respond here?
