### ISSUE TITLE
Webp logo

### ISSUE THREAD

**Issue by palmiak** [microlinkhq/metascraper#75]
Hi

When I scrape https://przekroj.pl/nauka/sabat-na-lysej-gorze-adam-weglowski microlink gets:
```
"logo": {
    "width": 192,
    "height": 192,
    "type": "webp",
    "url": "https://przekroj.pl/public/theme/favicons/xandroid-chrome-192x192.png.pagespeed.ic.8WQytfvF88.webp"
  },
```

But in code there is (when using firefox):
``` 
<link rel="icon" type="image/png" href="/public/theme/favicons/xandroid-chrome-192x192.png.pagespeed.ic.3NUQnUDELj.png" sizes="192x192">
```

or (when using chrome)
```
<link rel="icon" type="image/png" href="/public/theme/favicons/xandroid-chrome-192x192.png.pagespeed.ic.8WQytfvF88.webp" sizes="192x192">
```

Not all browsers are using webp so pulling them is not the best option. I think that the easiest way would be to not set microlink's scraper headers as Chrome/Webkit etc.

**Comment by Kikobeats** [comment]
I think you're right!

Microlink uses Headless Browser under the that, that's the reason why a `webp` image is served from the server behind the url.

Could do you try something? Can you setup a different `user-agent` using Chrome? It should be serve you a the `png` version

**Comment by palmiak** [comment]
I'm using https://api.microlink.io with curl for a digg-like functionality.

So even if I add the headers to api.microlink it doesn't matter because the api's headers are important for scraped website.

**Comment by Kikobeats** [comment]
oh ok, let me try, I'm going to ping you asap 🙂

**Comment by Kikobeats** [comment]
Should be looks fine now!

https://api.microlink.io/?url=https://przekroj.pl/nauka/sabat-na-lysej-gorze-adam-weglowski
