### ISSUE TITLE
Get Type of website url like Article/video/news

### ISSUE THREAD

**Issue by myfavsin** [microlinkhq/metascraper#80]
### Prerequisites

- [ ] I'm using the last version.
- [ ] My node version is the same as declared as `package.json`.

### Subject of the issue

Describe your issue here.

### Steps to reproduce

Tell us how to reproduce this issue.

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

**Comment by Kikobeats** [comment]
actually you can do that doing something like:

```
const isVideo = !!payload.data.video
```

I'm happy to add this feature if you add more information:

- what kind? look article/news is the same.
- what rules?

**Comment by myfavsin** [comment]
Hi,
Thanks for quick response.
If i want to get "og:type" of particlar url how do i get?
