### ISSUE TITLE
Add XSS Protection

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/metascraper#96]
Due to the nature of the library, a well direct XSS attack will be done.

In order to avoid it is necessary an extract check for each value extracted from the HTML, using one of the following approaches:

- https://github.com/cure53/DOMPurify → NOPE, it's only client side :(
- https://github.com/RisingStack/protect/blob/master/lib/rules/xss.js
- https://github.com/yahoo/xss-filters

Checkers

- https://github.com/s0md3v/XSStrike

Also is necessary keep in mind the performance implication of this change in the codebase.

**Comment by gobengo** [comment]
Until this is done, npm complains about using metascraper https://www.npmjs.com/advisories/603

**Comment by santiagopuentep** [comment]
This shouldn't be closed!

**Comment by Kikobeats** [comment]
Actually, it's open 🙂

I understand that's important but my life and my job day don't depend on this and this project.

so again, PRs are welcome!

**Comment by twogood** [comment]
New PR #169

**Comment by michailw** [comment]
This issue should remain open. NPM audit still marks this package as vulnerable: https://www.npmjs.com/advisories/603

**Comment by twogood** [comment]
Maybe someone need to tell them to re-evaluate the advisory?

**Comment by michailw** [comment]
@twogood I have sent an email to security@npmjs.org
I will update this thread with their answer.

**Comment by Kikobeats** [comment]
@michailw Thanks for that!

**Comment by michailw** [comment]
NPM updated advisory #603. metascraper is not marked as vulnerable since version 5.3.
